# Form implementation generated from reading ui file 'app/ui/chart_monitor_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChartMonitorDialog(object):
    def setupUi(self, ChartMonitorDialog):
        ChartMonitorDialog.setObjectName("ChartMonitorDialog")
        ChartMonitorDialog.resize(1100, 750)
        ChartMonitorDialog.setStyleSheet("QDialog {\n"
"  background-color: #002f00;\n"
"  color: #ffffff;\n"
"  font-family: \'Roboto\';\n"
"  border: 2px solid #4CAF50;\n"
"  border-radius: 6px;\n"
"}\n"
"\n"
"QLabel {\n"
"  color: #ffffff;\n"
"  font-size: 18px; \n"
"  font-weight: 500;\n"
"}\n"
"\n"
"QComboBox {\n"
"  background-color: rgba(0, 10, 0, 0.8);\n"
"  border: 1px solid #328844;\n"
"  color: #ffffff;\n"
"  padding: 4px;\n"
"  font-size: 18px;\n"
"  border-radius: 3px;\n"
"  min-width: 150px;\n"
"}\n"
"\n"
"QComboBox::drop-down { \n"
"    width: 18px; \n"
"}\n"
"\n"
"QComboBox::down-arrow { \n"
"    width: 14px; \n"
"    height: 14px; \n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #002f00;\n"
"    color: #ffffff;\n"
"    selection-background-color: #328844;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"/* Кнопки */\n"
"QPushButton {\n"
"  border: 1px solid #328844;\n"
"  background-color: rgba(0, 30, 0, 0.8);\n"
"  color: #ffffff;\n"
"  font-size: 18px;\n"
"  padding: 6px 15px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #004400;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #4CAF50;\n"
"  color: #002509;\n"
"}\n"
"\n"
"/* Специфічний стиль для кнопки Паузи, коли вона натиснута (активна) */\n"
"QPushButton:checked {\n"
"  background-color: #4CAF50;\n"
"  color: #002509;\n"
"}\n"
"\n"
"/* Чекбокс */\n"
"QCheckBox {\n"
"    color: #ffffff;\n"
"    font-size: 16px;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    background-color: rgba(0, 10, 0, 0.8);\n"
"    border: 1px solid #328844;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #4CAF50;\n"
"    border: 1px solid #4CAF50;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 1px solid #00ff00;\n"
"}\n"
"\n"
"/* Контейнер графіка - робимо його схожим на таблицю з прикладу */\n"
"QWidget#chartContainer {\n"
"  background-color: rgba(0, 10, 0, 0.3);\n"
"  border: 1px solid #328844;\n"
"  border-radius: 4px;\n"
"}\n"
"")
        self.chartContainer = QtWidgets.QWidget(parent=ChartMonitorDialog)
        self.chartContainer.setGeometry(QtCore.QRect(15, 70, 1070, 665))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chartContainer.sizePolicy().hasHeightForWidth())
        self.chartContainer.setSizePolicy(sizePolicy)
        self.chartContainer.setObjectName("chartContainer")
        self.chartContainerLayout = QtWidgets.QVBoxLayout(self.chartContainer)
        self.chartContainerLayout.setContentsMargins(0, 0, 0, 0)
        self.chartContainerLayout.setSpacing(0)
        self.chartContainerLayout.setObjectName("chartContainerLayout")
        self.layoutWidget = QtWidgets.QWidget(parent=ChartMonitorDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(16, 10, 1061, 40))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelSource = QtWidgets.QLabel(parent=self.layoutWidget)
        self.labelSource.setObjectName("labelSource")
        self.horizontalLayout.addWidget(self.labelSource)
        self.comboSource = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.comboSource.setMinimumSize(QtCore.QSize(160, 0))
        self.comboSource.setObjectName("comboSource")
        self.comboSource.addItem("")
        self.comboSource.addItem("")
        self.horizontalLayout.addWidget(self.comboSource)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelMode = QtWidgets.QLabel(parent=self.layoutWidget)
        self.labelMode.setObjectName("labelMode")
        self.horizontalLayout.addWidget(self.labelMode)
        self.comboChart = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.comboChart.setObjectName("comboChart")
        self.comboChart.addItem("")
        self.comboChart.addItem("")
        self.comboChart.addItem("")
        self.horizontalLayout.addWidget(self.comboChart)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnPause = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnPause.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPause.setCheckable(True)
        self.btnPause.setChecked(False)
        self.btnPause.setObjectName("btnPause")
        self.horizontalLayout.addWidget(self.btnPause)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnResetZoom = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnResetZoom.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnResetZoom.setObjectName("btnResetZoom")
        self.horizontalLayout.addWidget(self.btnResetZoom)
        self.btnClose = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnClose.setCheckable(False)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.horizontalLayout.setStretch(5, 1)

        self.retranslateUi(ChartMonitorDialog)
        QtCore.QMetaObject.connectSlotsByName(ChartMonitorDialog)

    def retranslateUi(self, ChartMonitorDialog):
        _translate = QtCore.QCoreApplication.translate
        ChartMonitorDialog.setWindowTitle(_translate("ChartMonitorDialog", "Моніторинг сигналів у реальному часі"))
        self.labelSource.setText(_translate("ChartMonitorDialog", "Сигнал:"))
        self.comboSource.setItemText(0, _translate("ChartMonitorDialog", "RF"))
        self.comboSource.setItemText(1, _translate("ChartMonitorDialog", "Sound"))
        self.labelMode.setText(_translate("ChartMonitorDialog", "Графік:"))
        self.comboChart.setItemText(0, _translate("ChartMonitorDialog", "Всі графіки (Both)"))
        self.comboChart.setItemText(1, _translate("ChartMonitorDialog", "Лише Спектр (Spectrum)"))
        self.comboChart.setItemText(2, _translate("ChartMonitorDialog", "Лише Водоспад (Waterfall)"))
        self.btnPause.setText(_translate("ChartMonitorDialog", "Пауза"))
        self.btnResetZoom.setText(_translate("ChartMonitorDialog", "Скинути"))
        self.btnClose.setText(_translate("ChartMonitorDialog", "Закрити"))
