# Form implementation generated from reading ui file 'app/ui/change_pwd_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChangePwdDialog(object):
    def setupUi(self, ChangePwdDialog):
        ChangePwdDialog.setObjectName("ChangePwdDialog")
        ChangePwdDialog.resize(920, 780)
        ChangePwdDialog.setMinimumSize(QtCore.QSize(920, 0))
        ChangePwdDialog.setStyleSheet("/* Головний фон діалогу - такий самий, як у твого MainWindow */\n"
"QDialog#ChangePwdDialog {\n"
"    background-color: rgba(0, 47, 0, 139);\n"
"}\n"
"\n"
"/* Стилізація всіх віджетів, щоб вони відповідали твоїй темі */\n"
"QLabel {\n"
"    font-family: \'Roboto\';\n"
"    font-size: 20px;\n"
"    color: #FFFFFF;\n"
"    background: none;\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit, QComboBox {\n"
"    font-family: \'Roboto\';\n"
"    font-size: 18px;\n"
"    color: #FFFFFF;\n"
"    background-color: rgba(0, 20, 0, 0.8);\n"
"    border: 1px solid #328844;\n"
"    padding: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #002509; /* Темний фон для списку */\n"
"    color: #FFFFFF;\n"
"    selection-background-color: #328844; /* Зелений при виборі */\n"
"    selection-color: #FFFFFF;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-family: \'Roboto\';\n"
"    font-size: 16px;\n"
"    color: #FFFFFF;\n"
"    background: none;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border: 1px solid #328844;\n"
"    background-color: rgba(0, 20, 0, 0.8);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #50E37F; /* Яскраво-зелена галочка */\n"
"    image: url(:/images/checkbox_checked_icon.png); /* (Опціонально) якщо маєш свою іконку галочки */\n"
"}\n"
"")
        ChangePwdDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ChangePwdDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loginFrame = QtWidgets.QFrame(parent=ChangePwdDialog)
        self.loginFrame.setMinimumSize(QtCore.QSize(400, 0))
        self.loginFrame.setMaximumSize(QtCore.QSize(400, 16777215))
        self.loginFrame.setStyleSheet("/* Рамка, як у твоїх віджетів в головному вікні */\n"
"QFrame#loginFrame {\n"
"    background: rgba(0, 10, 0, 0.8);\n"
"    border: 2px solid #328844;\n"
"    border-radius: 10px;\n"
"}")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.frameLayout = QtWidgets.QVBoxLayout(self.loginFrame)
        self.frameLayout.setContentsMargins(25, 20, 25, 20)
        self.frameLayout.setSpacing(15)
        self.frameLayout.setObjectName("frameLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("font-size: 28px;\n"
"font-weight: 600;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.frameLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.frameLayout.addItem(spacerItem)
        self.passwordContainer = QtWidgets.QWidget(parent=self.loginFrame)
        self.passwordContainer.setEnabled(True)
        self.passwordContainer.setStyleSheet("background: none;")
        self.passwordContainer.setObjectName("passwordContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.passwordContainer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.passwordLabel = QtWidgets.QLabel(parent=self.passwordContainer)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout_2.addWidget(self.passwordLabel)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=self.passwordContainer)
        self.passwordLineEdit.setMaximumSize(QtCore.QSize(295, 16777215))
        self.passwordLineEdit.setText("")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout_3.addWidget(self.passwordLineEdit, 0, 0, 1, 1)
        self.passwordHideBtn = QtWidgets.QPushButton(parent=self.passwordContainer)
        self.passwordHideBtn.setMinimumSize(QtCore.QSize(42, 42))
        self.passwordHideBtn.setMaximumSize(QtCore.QSize(42, 42))
        self.passwordHideBtn.setStyleSheet("QPushButton[id=\"eye_btn\"]{\n"
"    border: 2px solid #328844;\n"
"border-radius:8px;\n"
"    background-repeat:no-repeat;\n"
"background-position:center;\n"
"background-color:transparent;\n"
"}\n"
"\n"
"QPushButton[id=\"eye_btn\"][status=\"hidden\"]{\n"
"background-image:url(:/icons/eye_off.png);\n"
"}\n"
"\n"
"QPushButton[id=\"eye_btn\"][status=\"unhidden\"]{\n"
"background-image:url(:/icons/eye_on.png);\n"
"}")
        self.passwordHideBtn.setText("")
        self.passwordHideBtn.setObjectName("passwordHideBtn")
        self.gridLayout_3.addWidget(self.passwordHideBtn, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.errorWidget_1 = QtWidgets.QWidget(parent=self.passwordContainer)
        self.errorWidget_1.setMinimumSize(QtCore.QSize(0, 20))
        self.errorWidget_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.errorWidget_1.setVisible(False)
        self.errorWidget_1.setObjectName("errorWidget_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.errorWidget_1)
        self.gridLayout_2.setContentsMargins(0, 5, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.passwordIncorrectLabel = QtWidgets.QLabel(parent=self.errorWidget_1)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.passwordIncorrectLabel.setFont(font)
        self.passwordIncorrectLabel.setStyleSheet("QLabel[status=\"error\"]{\n"
"font-size:18px;\n"
"color:darkred;\n"
"margin-left:8px;\n"
"}")
        self.passwordIncorrectLabel.setWordWrap(True)
        self.passwordIncorrectLabel.setObjectName("passwordIncorrectLabel")
        self.gridLayout_2.addWidget(self.passwordIncorrectLabel, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.errorWidget_1)
        self.confirmPasswordLabel = QtWidgets.QLabel(parent=self.passwordContainer)
        self.confirmPasswordLabel.setObjectName("confirmPasswordLabel")
        self.verticalLayout_2.addWidget(self.confirmPasswordLabel)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setHorizontalSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.confirmPasswordLineEdit = QtWidgets.QLineEdit(parent=self.passwordContainer)
        self.confirmPasswordLineEdit.setMaximumSize(QtCore.QSize(295, 16777215))
        self.confirmPasswordLineEdit.setText("")
        self.confirmPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.confirmPasswordLineEdit.setObjectName("confirmPasswordLineEdit")
        self.gridLayout_4.addWidget(self.confirmPasswordLineEdit, 0, 0, 1, 1)
        self.confirmPasswordHideBtn = QtWidgets.QPushButton(parent=self.passwordContainer)
        self.confirmPasswordHideBtn.setMinimumSize(QtCore.QSize(42, 42))
        self.confirmPasswordHideBtn.setMaximumSize(QtCore.QSize(42, 42))
        self.confirmPasswordHideBtn.setStyleSheet("QPushButton[id=\"eye_btn\"]{\n"
"    border: 2px solid #328844;\n"
"border-radius:8px;\n"
"    background-repeat:no-repeat;\n"
"background-position:center;\n"
"background-color:transparent;\n"
"}\n"
"\n"
"QPushButton[id=\"eye_btn\"][status=\"hidden\"]{\n"
"background-image:url(:/icons/eye_off.png);\n"
"}\n"
"\n"
"QPushButton[id=\"eye_btn\"][status=\"unhidden\"]{\n"
"background-image:url(:/icons/eye_on.png);\n"
"}")
        self.confirmPasswordHideBtn.setText("")
        self.confirmPasswordHideBtn.setObjectName("confirmPasswordHideBtn")
        self.gridLayout_4.addWidget(self.confirmPasswordHideBtn, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.errorWidget_2 = QtWidgets.QWidget(parent=self.passwordContainer)
        self.errorWidget_2.setMinimumSize(QtCore.QSize(0, 20))
        self.errorWidget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.errorWidget_2.setVisible(False)
        self.errorWidget_2.setObjectName("errorWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.errorWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.confirmPasswordIncorrectLabel = QtWidgets.QLabel(parent=self.errorWidget_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.confirmPasswordIncorrectLabel.setFont(font)
        self.confirmPasswordIncorrectLabel.setStyleSheet("QLabel[status=\"error\"]{\n"
"font-size:18px;\n"
"color:darkred;\n"
"margin-left:8px;\n"
"}")
        self.confirmPasswordIncorrectLabel.setWordWrap(True)
        self.confirmPasswordIncorrectLabel.setObjectName("confirmPasswordIncorrectLabel")
        self.gridLayout.addWidget(self.confirmPasswordIncorrectLabel, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.errorWidget_2)
        self.frameLayout.addWidget(self.passwordContainer)
        self.saveButton = QtWidgets.QPushButton(parent=self.loginFrame)
        self.saveButton.setMinimumSize(QtCore.QSize(320, 100))
        self.saveButton.setStyleSheet("\n"
"QPushButton{\n"
"    border: none;\n"
"    background-image: url(:/images/Btn_MainMenu_off.png);\n"
"    background-position:center;\n"
"    min-width:320px;\n"
"    max-width:320px;\n"
"    height:100px;\n"
"    font-family: \'Roboto\';\n"
"    font-weight: 500;\n"
"    font-size: 24px;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: none;\n"
"    background-image: url(:/images/Btn_MainMenu_on.png);\n"
"    font-family: \'Roboto\';\n"
"    font-weight: 500;\n"
"    font-size: 24px;\n"
"    color: #002509;\n"
"}\n"
"\n"
"QPushButton[enabled=\"false\"]{\n"
"    border: none;\n"
"    background-image: url(:/images/Btn_MainMenu_disabled.png);\n"
"    color: #FFFFFF;\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.frameLayout.addWidget(self.saveButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.loginFrame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(ChangePwdDialog)
        QtCore.QMetaObject.connectSlotsByName(ChangePwdDialog)

    def retranslateUi(self, ChangePwdDialog):
        _translate = QtCore.QCoreApplication.translate
        ChangePwdDialog.setWindowTitle(_translate("ChangePwdDialog", "Зміна паролю"))
        self.titleLabel.setText(_translate("ChangePwdDialog", "ЗМІНА ПАРОЛЮ"))
        self.passwordLabel.setText(_translate("ChangePwdDialog", "Введіть пароль:"))
        self.passwordLineEdit.setPlaceholderText(_translate("ChangePwdDialog", "Введіть пароль"))
        self.passwordHideBtn.setProperty("id", _translate("ChangePwdDialog", "eye_btn"))
        self.passwordHideBtn.setProperty("status", _translate("ChangePwdDialog", "hidden"))
        self.passwordIncorrectLabel.setText(_translate("ChangePwdDialog", "Паролі не співпадають"))
        self.passwordIncorrectLabel.setProperty("status", _translate("ChangePwdDialog", "error"))
        self.confirmPasswordLabel.setText(_translate("ChangePwdDialog", "Підтвердіть пароль:"))
        self.confirmPasswordLineEdit.setPlaceholderText(_translate("ChangePwdDialog", "Введіть пароль"))
        self.confirmPasswordHideBtn.setProperty("id", _translate("ChangePwdDialog", "eye_btn"))
        self.confirmPasswordHideBtn.setProperty("status", _translate("ChangePwdDialog", "hidden"))
        self.confirmPasswordIncorrectLabel.setText(_translate("ChangePwdDialog", "Паролі не співпадають"))
        self.confirmPasswordIncorrectLabel.setProperty("status", _translate("ChangePwdDialog", "error"))
        self.saveButton.setText(_translate("ChangePwdDialog", "Зберегти"))
