# Form implementation generated from reading ui file 'app/ui/class_manager_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ClassManagerDialog(object):
    def setupUi(self, ClassManagerDialog):
        ClassManagerDialog.setObjectName("ClassManagerDialog")
        ClassManagerDialog.resize(450, 550)
        ClassManagerDialog.setStyleSheet("QDialog { background-color: #002f00; color: #fff; font-family: \'Roboto\'; }\n"
"QListWidget { background-color: rgba(0, 10, 0, 0.6); border: 1px solid #328844; color: #fff; font-size: 18px; }\n"
"QListWidget::item { padding: 5px; }\n"
"QListWidget::item:selected { background-color: #328844; color: #fff; }\n"
"\n"
"QLineEdit { \n"
"    background-color: rgba(0, 10, 0, 0.8); \n"
"    border: 1px solid #328844; \n"
"    color: #fff; \n"
"    font-size: 18px; \n"
"    padding: 5px; \n"
"    margin-bottom: 5px;\n"
"}\n"
"\n"
"QPushButton { background-color: rgba(0, 20, 0, 0.8); border: 1px solid #328844; color: #fff; font-size: 18px; padding: 6px; border-radius: 4px; }\n"
"QPushButton:pressed { background-color: #4CAF50; }\n"
"QPushButton#btnDelete { border-color: #aa3333; }\n"
"QPushButton#btnDelete:pressed { background-color: #aa3333; }")
        self.horizontalLayout = QtWidgets.QHBoxLayout(ClassManagerDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lstClasses = QtWidgets.QListWidget(parent=ClassManagerDialog)
        self.lstClasses.setObjectName("lstClasses")
        self.horizontalLayout.addWidget(self.lstClasses)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.keyboardContainer = QtWidgets.QWidget(parent=ClassManagerDialog)
        self.keyboardContainer.setMinimumSize(QtCore.QSize(165, 135))
        self.keyboardContainer.setMaximumSize(QtCore.QSize(165, 135))
        self.keyboardContainer.setObjectName("keyboardContainer")
        self.keyboardLayout = QtWidgets.QVBoxLayout(self.keyboardContainer)
        self.keyboardLayout.setContentsMargins(0, 0, 0, 0)
        self.keyboardLayout.setSpacing(0)
        self.keyboardLayout.setObjectName("keyboardLayout")
        self.verticalLayout.addWidget(self.keyboardContainer)
        self.inpClassName = QtWidgets.QLineEdit(parent=ClassManagerDialog)
        self.inpClassName.setObjectName("inpClassName")
        self.verticalLayout.addWidget(self.inpClassName)
        self.btnAdd = QtWidgets.QPushButton(parent=ClassManagerDialog)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout.addWidget(self.btnAdd)
        self.btnClearSelection = QtWidgets.QPushButton(parent=ClassManagerDialog)
        self.btnClearSelection.setObjectName("btnClearSelection")
        self.verticalLayout.addWidget(self.btnClearSelection)
        self.btnDelete = QtWidgets.QPushButton(parent=ClassManagerDialog)
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout.addWidget(self.btnDelete)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btnClose = QtWidgets.QPushButton(parent=ClassManagerDialog)
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout.addWidget(self.btnClose)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(ClassManagerDialog)
        QtCore.QMetaObject.connectSlotsByName(ClassManagerDialog)

    def retranslateUi(self, ClassManagerDialog):
        _translate = QtCore.QCoreApplication.translate
        ClassManagerDialog.setWindowTitle(_translate("ClassManagerDialog", "Керування класами"))
        self.inpClassName.setPlaceholderText(_translate("ClassManagerDialog", "Назва класу..."))
        self.btnAdd.setText(_translate("ClassManagerDialog", "Додати / Зберегти"))
        self.btnClearSelection.setText(_translate("ClassManagerDialog", "Очистити вибір"))
        self.btnClearSelection.setToolTip(_translate("ClassManagerDialog", "Скинути вибір для створення нового класу"))
        self.btnDelete.setText(_translate("ClassManagerDialog", "Видалити"))
        self.btnClose.setText(_translate("ClassManagerDialog", "Закрити"))
