# Form implementation generated from reading ui file 'app/ui/keyboard_widget.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_KeyboardWidget(object):
    def setupUi(self, KeyboardWidget):
        KeyboardWidget.setObjectName("KeyboardWidget")
        KeyboardWidget.resize(141, 111)
        KeyboardWidget.setStyleSheet(
            "#LanguageFrame {\n"
            "    background: rgba(0, 10, 0, 0.8);\n"
            "    border: 2px solid #328844;\n"
            "}"
        )
        self.LanguageFrame = QtWidgets.QFrame(parent=KeyboardWidget)
        self.LanguageFrame.setGeometry(QtCore.QRect(0, 0, 141, 111))
        self.LanguageFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.LanguageFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.LanguageFrame.setObjectName("LanguageFrame")
        self.langLabel = QtWidgets.QLabel(parent=self.LanguageFrame)
        self.langLabel.setGeometry(QtCore.QRect(10, 0, 91, 41))
        self.langLabel.setStyleSheet(
            "font-family: 'Roboto';\n"
            "font-size:30px;\n"
            "border:none;\n"
            "background-color:transparent;\n"
            "color:#fff;"
        )
        self.langLabel.setObjectName("langLabel")
        self.langComboBox = QtWidgets.QComboBox(parent=self.LanguageFrame)
        self.langComboBox.setGeometry(QtCore.QRect(10, 50, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.langComboBox.setFont(font)
        self.langComboBox.setStyleSheet(
            "QComboBox {\n"
            "      font-family: 'Roboto';\n"
            "      font-size: 28px;\n"
            "      color: #FFFFFF;\n"
            "      background-color: rgba(0, 20, 0, 0.8);\n"
            "      border: 2px solid #328844;\n"
            "      padding: 8px;\n"
            "      border-radius: 4px;\n"
            "}\n"
            "\n"
            "QComboBox QAbstractItemView{\n"
            "    background-color: #002509; \n"
            "    color: #FFFFFF;\n"
            "    selection-background-color: #328844; \n"
            "    selection-color: #FFFFFF;\n"
            "}"
        )
        self.langComboBox.setObjectName("langComboBox")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")

        self.retranslateUi(KeyboardWidget)
        QtCore.QMetaObject.connectSlotsByName(KeyboardWidget)

    def retranslateUi(self, KeyboardWidget):
        _translate = QtCore.QCoreApplication.translate
        self.langLabel.setText(_translate("KeyboardWidget", "Мова:"))
        self.langComboBox.setItemText(0, _translate("KeyboardWidget", "EN"))
        self.langComboBox.setItemText(1, _translate("KeyboardWidget", "UA"))
