# Form implementation generated from reading ui file 'app/ui/login_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(920, 780)
        LoginDialog.setMinimumSize(QtCore.QSize(920, 0))
        LoginDialog.setStyleSheet("/* Головний фон діалогу - такий самий, як у твого MainWindow */\n"
"QDialog#LoginDialog {\n"
"    background-color: rgba(0, 47, 0, 139);\n"
"}\n"
"\n"
"/* Стилізація всіх віджетів, щоб вони відповідали твоїй темі */\n"
"QLabel {\n"
"    font-family: \'Roboto\';\n"
"    font-size: 20px;\n"
"    color: #FFFFFF;\n"
"    background: none;\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit, QComboBox {\n"
"    font-family: \'Roboto\';\n"
"    font-size: 18px;\n"
"    color: #FFFFFF;\n"
"    background-color: rgba(0, 20, 0, 0.8);\n"
"    border: 1px solid #328844;\n"
"    padding: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #002509; /* Темний фон для списку */\n"
"    color: #FFFFFF;\n"
"    selection-background-color: #328844; /* Зелений при виборі */\n"
"    selection-color: #FFFFFF;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-family: \'Roboto\';\n"
"    font-size: 16px;\n"
"    color: #FFFFFF;\n"
"    background: none;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border: 1px solid #328844;\n"
"    background-color: rgba(0, 20, 0, 0.8);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #50E37F; /* Яскраво-зелена галочка */\n"
"    image: url(:/images/checkbox_checked_icon.png); /* (Опціонально) якщо маєш свою іконку галочки */\n"
"}\n"
"")
        LoginDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.loginFrame = QtWidgets.QFrame(parent=LoginDialog)
        self.loginFrame.setMinimumSize(QtCore.QSize(400, 0))
        self.loginFrame.setMaximumSize(QtCore.QSize(400, 16777215))
        self.loginFrame.setStyleSheet("/* Рамка, як у твоїх віджетів в головному вікні */\n"
"QFrame#loginFrame {\n"
"    background: rgba(0, 10, 0, 0.8);\n"
"    border: 2px solid #328844;\n"
"    border-radius: 10px;\n"
"}")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.frameLayout = QtWidgets.QVBoxLayout(self.loginFrame)
        self.frameLayout.setContentsMargins(25, 20, 25, 20)
        self.frameLayout.setSpacing(15)
        self.frameLayout.setObjectName("frameLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("font-size: 28px;\n"
"font-weight: 600;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.frameLayout.addWidget(self.titleLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.frameLayout.addItem(spacerItem1)
        self.roleLabel = QtWidgets.QLabel(parent=self.loginFrame)
        self.roleLabel.setStyleSheet("QLabel{\n"
"font-size:22px;\n"
"}")
        self.roleLabel.setObjectName("roleLabel")
        self.frameLayout.addWidget(self.roleLabel)
        self.roleComboBox = QtWidgets.QComboBox(parent=self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        self.roleComboBox.setFont(font)
        self.roleComboBox.setStyleSheet("QComboBox{\n"
"font-size:22px;\n"
"}")
        self.roleComboBox.setObjectName("roleComboBox")
        self.roleComboBox.addItem("")
        self.roleComboBox.addItem("")
        self.frameLayout.addWidget(self.roleComboBox)
        self.passwordContainer = QtWidgets.QWidget(parent=self.loginFrame)
        self.passwordContainer.setEnabled(True)
        self.passwordContainer.setVisible(False)
        self.passwordContainer.setStyleSheet("background: none;")
        self.passwordContainer.setObjectName("passwordContainer")
        self.gridLayout = QtWidgets.QGridLayout(self.passwordContainer)
        self.gridLayout.setContentsMargins(0, 5, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=self.passwordContainer)
        self.widget.setMinimumSize(QtCore.QSize(0, 24))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 24))
        self.widget.setObjectName("widget")
        self.passwordIncorrectLabel = QtWidgets.QLabel(parent=self.widget)
        self.passwordIncorrectLabel.setGeometry(QtCore.QRect(10, 0, 201, 22))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        self.passwordIncorrectLabel.setFont(font)
        self.passwordIncorrectLabel.setVisible(False)
        self.passwordIncorrectLabel.setStyleSheet("QLabel[status=\"error\"]{\n"
"font-size:18px;\n"
"color:darkred;\n"
"margin-left:8px;\n"
"}")
        self.passwordIncorrectLabel.setObjectName("passwordIncorrectLabel")
        self.gridLayout.addWidget(self.widget, 3, 0, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(parent=self.passwordContainer)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 0, 0, 1, 1)
        self.rememberCheckBox = QtWidgets.QCheckBox(parent=self.passwordContainer)
        self.rememberCheckBox.setObjectName("rememberCheckBox")
        self.gridLayout.addWidget(self.rememberCheckBox, 4, 0, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=self.passwordContainer)
        self.passwordLineEdit.setMaximumSize(QtCore.QSize(295, 16777215))
        self.passwordLineEdit.setText("")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 2, 0, 1, 1)
        self.passwordHideBtn = QtWidgets.QPushButton(parent=self.passwordContainer)
        self.passwordHideBtn.setMinimumSize(QtCore.QSize(0, 42))
        self.passwordHideBtn.setMaximumSize(QtCore.QSize(42, 42))
        self.passwordHideBtn.setStyleSheet("QPushButton[id=\"eye_btn\"]{\n"
"    border: 2px solid #328844;\n"
"border-radius:8px;\n"
"    background-repeat:no-repeat;\n"
"background-position:center;\n"
"background-color:transparent;\n"
"}\n"
"\n"
"QPushButton[id=\"eye_btn\"][status=\"hidden\"]{\n"
"background-image:url(:/icons/eye_off.png);\n"
"}\n"
"\n"
"QPushButton[id=\"eye_btn\"][status=\"unhidden\"]{\n"
"background-image:url(:/icons/eye_on.png);\n"
"}")
        self.passwordHideBtn.setText("")
        self.passwordHideBtn.setObjectName("passwordHideBtn")
        self.gridLayout.addWidget(self.passwordHideBtn, 2, 1, 1, 1)
        self.frameLayout.addWidget(self.passwordContainer)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.frameLayout.addItem(spacerItem2)
        self.loginButton = QtWidgets.QPushButton(parent=self.loginFrame)
        self.loginButton.setMinimumSize(QtCore.QSize(320, 60))
        self.loginButton.setStyleSheet("\n"
"QPushButton{\n"
"    border: none;\n"
"    background-image: url(:/images/Btn_MainMenu_off.png);\n"
"    background-position:center;\n"
"    min-width:320px;\n"
"    max-width:320px;\n"
"    height:100px;\n"
"    font-family: \'Roboto\';\n"
"    font-weight: 500;\n"
"    font-size: 24px;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: none;\n"
"    background-image: url(:/images/Btn_MainMenu_on.png);\n"
"    font-family: \'Roboto\';\n"
"    font-weight: 500;\n"
"    font-size: 24px;\n"
"    color: #002509;\n"
"}\n"
"\n"
"QPushButton[enabled=\"false\"]{\n"
"    border: none;\n"
"    background-image: url(:/images/Btn_MainMenu_disabled.png);\n"
"    color: #FFFFFF;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.frameLayout.addWidget(self.loginButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.loginFrame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Авторизація"))
        self.titleLabel.setText(_translate("LoginDialog", "АВТОРИЗАЦІЯ"))
        self.roleLabel.setText(_translate("LoginDialog", "Оберіть вашу роль:"))
        self.roleComboBox.setItemText(0, _translate("LoginDialog", "Оператор"))
        self.roleComboBox.setItemText(1, _translate("LoginDialog", "Власник"))
        self.passwordIncorrectLabel.setText(_translate("LoginDialog", "Пароль неправильний"))
        self.passwordIncorrectLabel.setProperty("status", _translate("LoginDialog", "error"))
        self.passwordLabel.setText(_translate("LoginDialog", "Пароль:"))
        self.rememberCheckBox.setText(_translate("LoginDialog", "Запам\'ятати мене"))
        self.passwordLineEdit.setPlaceholderText(_translate("LoginDialog", "Введіть пароль"))
        self.passwordHideBtn.setProperty("id", _translate("LoginDialog", "eye_btn"))
        self.passwordHideBtn.setProperty("status", _translate("LoginDialog", "hidden"))
        self.loginButton.setText(_translate("LoginDialog", "Увійти"))
