# Form implementation generated from reading ui file 'app/ui/log_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LogDialog(object):
    def setupUi(self, LogDialog):
        LogDialog.setObjectName("LogDialog")
        LogDialog.resize(1400, 762)
        LogDialog.setStyleSheet("QDialog {\n"
"  background-color: #002f00;\n"
"  color: #ffffff;\n"
"  font-family: \'Roboto\';\n"
"  border: 2px solid #4CAF50;\n"
"  border-radius: 6px;\n"
"}\n"
"\n"
"QLabel {\n"
"  color: #ffffff;\n"
"  font-size: 18px; \n"
"  font-weight: 500;\n"
"}\n"
"\n"
"QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox, QDateTimeEdit {\n"
"  background-color: rgba(0, 10, 0, 0.8);\n"
"  border: 1px solid #328844;\n"
"  color: #ffffff;\n"
"  padding: 4px;\n"
"  font-size: 18px;\n"
"  border-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow { width: 16px; height: 16px; padding:2px }\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #002f00;\n"
"    color: #ffffff;\n"
"    selection-background-color: #328844;\n"
"}\n"
"\n"
"/* Кнопки календаря */\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button,\n"
"QSpinBox::up-button, QSpinBox::down-button, QDateTimeEdit::up-button, QDateTimeEdit::down-button {\n"
" width: 14px; \n"
" height: 14px; \n"
" padding:2px \n"
"}\n"
"\n"
"/* Календар */\n"
"QCalendarWidget QWidget {\n"
"    background-color: #002f00;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Таблиця */\n"
"QTableWidget {\n"
"  background-color: rgba(0, 10, 0, 0.3);\n"
"  gridline-color: #328844;\n"
"  border: 1px solid #328844;\n"
"  font-size: 16px;\n"
"  color: #fff;\n"
"}\n"
"QHeaderView::section {\n"
"  background-color: #001a05;\n"
"  color: #4CAF50;\n"
"  padding: 4px;\n"
"  border: 1px solid #328844;\n"
"  font-weight: bold;\n"
"  font-size: 18px;\n"
"}\n"
"\n"
"QTableView{\n"
" font-size: 16px;\n"
"}\n"
"\n"
"QTableWidget::item{\n"
" font-size: 30px;\n"
"}\n"
"\n"
"/* Кнопки */\n"
"QPushButton {\n"
"  border: 1px solid #328844;\n"
"  background-color: rgba(0, 30, 0, 0.8);\n"
"  color: #ffffff;\n"
"  font-size: 18px;\n"
"  padding: 6px 15px;\n"
"  border-radius: 4px;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: #4CAF50;\n"
"  color: #002509;\n"
"}\n"
"\n"
"QPushButton#btnApplyFilters {\n"
"  background-color: #004400;\n"
"  font-weight: bold;\n"
"}\n"
"\n"
"/* Фрейм фільтрів */\n"
"QFrame#frameFilters {\n"
"    background-color: rgba(0, 20, 0, 0.5);\n"
"    border-right: 2px solid #328844;\n"
"}\n"
"\n"
"/* Групи */\n"
"QGroupBox {\n"
"    border: 1px solid #328844;\n"
"    border-radius: 5px;\n"
"    margin-top: 20px;\n"
"    font-weight: bold;\n"
"    color: #4CAF50;\n"
"    font-size:18px;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px;\n"
"    font-size:18px;\n"
"}\n"
"\n"
"QTabWidget::pane { border: 1px solid #328844; }\n"
"QTabBar::tab {\n"
"    background: #001a05;\n"
"    color: #888;\n"
"    padding: 8px 20px;\n"
"    border: 1px solid #328844;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    margin-right: 2px;\n"
"    font-size:18px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background: #328844;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#btnClose {\n"
"  background-color: #442222;\n"
"  border-color: #aa3333;\n"
"}\n"
"QPushButton#btnClose:pressed {\n"
"  background-color: #aa3333;\n"
"}\n"
"")
        self.horizontalLayout_Main = QtWidgets.QHBoxLayout(LogDialog)
        self.horizontalLayout_Main.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_Main.setSpacing(0)
        self.horizontalLayout_Main.setObjectName("horizontalLayout_Main")
        self.frameFilters = QtWidgets.QFrame(parent=LogDialog)
        self.frameFilters.setMinimumSize(QtCore.QSize(300, 0))
        self.frameFilters.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frameFilters.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frameFilters.setObjectName("frameFilters")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameFilters)
        self.verticalLayout.setContentsMargins(-1, 40, -1, 40)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblSessionTitle = QtWidgets.QLabel(parent=self.frameFilters)
        self.lblSessionTitle.setObjectName("lblSessionTitle")
        self.verticalLayout.addWidget(self.lblSessionTitle)
        self.cmbSessions = QtWidgets.QComboBox(parent=self.frameFilters)
        self.cmbSessions.setObjectName("cmbSessions")
        self.verticalLayout.addWidget(self.cmbSessions)
        self.grpFilters = QtWidgets.QGroupBox(parent=self.frameFilters)
        self.grpFilters.setObjectName("grpFilters")
        self.formLayout = QtWidgets.QFormLayout(self.grpFilters)
        self.formLayout.setVerticalSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.lblTime = QtWidgets.QLabel(parent=self.grpFilters)
        self.lblTime.setObjectName("lblTime")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTime)
        self.lblFilterName = QtWidgets.QLabel(parent=self.grpFilters)
        self.lblFilterName.setMinimumSize(QtCore.QSize(100, 0))
        self.lblFilterName.setObjectName("lblFilterName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFilterName)
        self.inpFilterName = QtWidgets.QLineEdit(parent=self.grpFilters)
        self.inpFilterName.setMaximumSize(QtCore.QSize(250, 16777215))
        self.inpFilterName.setObjectName("inpFilterName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.inpFilterName)
        self.lblFilterType = QtWidgets.QLabel(parent=self.grpFilters)
        self.lblFilterType.setObjectName("lblFilterType")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFilterType)
        self.lblDist = QtWidgets.QLabel(parent=self.grpFilters)
        self.lblDist.setObjectName("lblDist")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblDist)
        self.layoutDist = QtWidgets.QHBoxLayout()
        self.layoutDist.setSpacing(0)
        self.layoutDist.setObjectName("layoutDist")
        self.inpDistMin = QtWidgets.QSpinBox(parent=self.grpFilters)
        self.inpDistMin.setMinimumSize(QtCore.QSize(115, 0))
        self.inpDistMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.inpDistMin.setMaximum(50000)
        self.inpDistMin.setProperty("value", 0)
        self.inpDistMin.setObjectName("inpDistMin")
        self.layoutDist.addWidget(self.inpDistMin)
        self.lblDash = QtWidgets.QLabel(parent=self.grpFilters)
        self.lblDash.setMinimumSize(QtCore.QSize(20, 0))
        self.lblDash.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblDash.setObjectName("lblDash")
        self.layoutDist.addWidget(self.lblDash)
        self.inpDistMax = QtWidgets.QSpinBox(parent=self.grpFilters)
        self.inpDistMax.setMinimumSize(QtCore.QSize(115, 0))
        self.inpDistMax.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.inpDistMax.setMaximum(50000)
        self.inpDistMax.setProperty("value", 5000)
        self.inpDistMax.setObjectName("inpDistMax")
        self.layoutDist.addWidget(self.inpDistMax)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.layoutDist)
        self.lblAngle = QtWidgets.QLabel(parent=self.grpFilters)
        self.lblAngle.setObjectName("lblAngle")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblAngle)
        self.layoutAngle = QtWidgets.QHBoxLayout()
        self.layoutAngle.setSpacing(0)
        self.layoutAngle.setObjectName("layoutAngle")
        self.inpAngleMin = QtWidgets.QSpinBox(parent=self.grpFilters)
        self.inpAngleMin.setMinimumSize(QtCore.QSize(115, 0))
        self.inpAngleMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.inpAngleMin.setMaximum(360)
        self.inpAngleMin.setObjectName("inpAngleMin")
        self.layoutAngle.addWidget(self.inpAngleMin)
        self.lblDash2 = QtWidgets.QLabel(parent=self.grpFilters)
        self.lblDash2.setMinimumSize(QtCore.QSize(20, 0))
        self.lblDash2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblDash2.setObjectName("lblDash2")
        self.layoutAngle.addWidget(self.lblDash2)
        self.inpAngleMax = QtWidgets.QSpinBox(parent=self.grpFilters)
        self.inpAngleMax.setMinimumSize(QtCore.QSize(115, 0))
        self.inpAngleMax.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.inpAngleMax.setMaximum(360)
        self.inpAngleMax.setProperty("value", 360)
        self.inpAngleMax.setObjectName("inpAngleMax")
        self.layoutAngle.addWidget(self.inpAngleMax)
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.ItemRole.LabelRole, self.layoutAngle)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inpTimeStart = QtWidgets.QDateTimeEdit(parent=self.grpFilters)
        self.inpTimeStart.setCalendarPopup(True)
        self.inpTimeStart.setObjectName("inpTimeStart")
        self.horizontalLayout.addWidget(self.inpTimeStart)
        self.inpTimeEnd = QtWidgets.QDateTimeEdit(parent=self.grpFilters)
        self.inpTimeEnd.setCalendarPopup(True)
        self.inpTimeEnd.setObjectName("inpTimeEnd")
        self.horizontalLayout.addWidget(self.inpTimeEnd)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.horizontalLayout)
        self.cmbFilterType = QtWidgets.QComboBox(parent=self.grpFilters)
        self.cmbFilterType.setMaximumSize(QtCore.QSize(250, 16777215))
        self.cmbFilterType.setObjectName("cmbFilterType")
        self.cmbFilterType.addItem("")
        self.cmbFilterType.addItem("")
        self.cmbFilterType.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.cmbFilterType)
        self.verticalLayout.addWidget(self.grpFilters)
        self.btnApplyFilters = QtWidgets.QPushButton(parent=self.frameFilters)
        self.btnApplyFilters.setObjectName("btnApplyFilters")
        self.verticalLayout.addWidget(self.btnApplyFilters)
        self.btnResetFilters = QtWidgets.QPushButton(parent=self.frameFilters)
        self.btnResetFilters.setObjectName("btnResetFilters")
        self.verticalLayout.addWidget(self.btnResetFilters)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.btnClose = QtWidgets.QPushButton(parent=self.frameFilters)
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout.addWidget(self.btnClose)
        self.horizontalLayout_Main.addWidget(self.frameFilters)
        self.frameContent = QtWidgets.QFrame(parent=LogDialog)
        self.frameContent.setObjectName("frameContent")
        self.verticalLayout_Content = QtWidgets.QVBoxLayout(self.frameContent)
        self.verticalLayout_Content.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_Content.setObjectName("verticalLayout_Content")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.frameContent)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGeneral = QtWidgets.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.verticalLayout_Gen = QtWidgets.QVBoxLayout(self.tabGeneral)
        self.verticalLayout_Gen.setObjectName("verticalLayout_Gen")
        self.tableLogs = QtWidgets.QTableWidget(parent=self.tabGeneral)
        self.tableLogs.setObjectName("tableLogs")
        self.tableLogs.setColumnCount(7)
        self.tableLogs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableLogs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLogs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLogs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLogs.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLogs.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLogs.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLogs.setHorizontalHeaderItem(6, item)
        self.verticalLayout_Gen.addWidget(self.tableLogs)
        self.tabWidget.addTab(self.tabGeneral, "")
        self.tabGeneralAnalyze = QtWidgets.QWidget()
        self.tabGeneralAnalyze.setObjectName("tabGeneralAnalyze")
        self.verticalLayout_Obj = QtWidgets.QVBoxLayout(self.tabGeneralAnalyze)
        self.verticalLayout_Obj.setObjectName("verticalLayout_Obj")
        self.layoutChartControls = QtWidgets.QHBoxLayout()
        self.layoutChartControls.setObjectName("layoutChartControls")
        self.lblChartTypeGen = QtWidgets.QLabel(parent=self.tabGeneralAnalyze)
        self.lblChartTypeGen.setObjectName("lblChartTypeGen")
        self.layoutChartControls.addWidget(self.lblChartTypeGen)
        self.cmbChartTypeGeneral = QtWidgets.QComboBox(parent=self.tabGeneralAnalyze)
        self.cmbChartTypeGeneral.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbChartTypeGeneral.setObjectName("cmbChartTypeGeneral")
        self.cmbChartTypeGeneral.addItem("")
        self.cmbChartTypeGeneral.addItem("")
        self.layoutChartControls.addWidget(self.cmbChartTypeGeneral)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutChartControls.addItem(spacerItem1)
        self.verticalLayout_Obj.addLayout(self.layoutChartControls)
        self.chartContainerGeneral = QtWidgets.QFrame(parent=self.tabGeneralAnalyze)
        self.chartContainerGeneral.setMinimumSize(QtCore.QSize(0, 300))
        self.chartContainerGeneral.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.chartContainerGeneral.setObjectName("chartContainerGeneral")
        self.layoutChartGen = QtWidgets.QVBoxLayout(self.chartContainerGeneral)
        self.layoutChartGen.setObjectName("layoutChartGen")
        self.verticalLayout_Obj.addWidget(self.chartContainerGeneral)
        self.tabWidget.addTab(self.tabGeneralAnalyze, "")
        self.tabObject = QtWidgets.QWidget()
        self.tabObject.setObjectName("tabObject")
        self.verticalLayout_Obj1 = QtWidgets.QVBoxLayout(self.tabObject)
        self.verticalLayout_Obj1.setObjectName("verticalLayout_Obj1")
        self.layoutObjSel = QtWidgets.QHBoxLayout()
        self.layoutObjSel.setObjectName("layoutObjSel")
        self.lblSelObj = QtWidgets.QLabel(parent=self.tabObject)
        self.lblSelObj.setObjectName("lblSelObj")
        self.layoutObjSel.addWidget(self.lblSelObj)
        self.cmbTargetObject = QtWidgets.QComboBox(parent=self.tabObject)
        self.cmbTargetObject.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbTargetObject.setObjectName("cmbTargetObject")
        self.layoutObjSel.addWidget(self.cmbTargetObject)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutObjSel.addItem(spacerItem2)
        self.verticalLayout_Obj1.addLayout(self.layoutObjSel)
        self.layoutObjCharts = QtWidgets.QHBoxLayout()
        self.layoutObjCharts.setObjectName("layoutObjCharts")
        self.chartContainerPath = QtWidgets.QFrame(parent=self.tabObject)
        self.chartContainerPath.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.chartContainerPath.setObjectName("chartContainerPath")
        self.layoutChartPath = QtWidgets.QVBoxLayout(self.chartContainerPath)
        self.layoutChartPath.setObjectName("layoutChartPath")
        self.lblPathTitle = QtWidgets.QLabel(parent=self.chartContainerPath)
        self.lblPathTitle.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lblPathTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblPathTitle.setObjectName("lblPathTitle")
        self.layoutChartPath.addWidget(self.lblPathTitle)
        self.layoutObjCharts.addWidget(self.chartContainerPath)
        self.chartContainerSignal = QtWidgets.QFrame(parent=self.tabObject)
        self.chartContainerSignal.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.chartContainerSignal.setObjectName("chartContainerSignal")
        self.layoutChartSignal = QtWidgets.QVBoxLayout(self.chartContainerSignal)
        self.layoutChartSignal.setObjectName("layoutChartSignal")
        self.lblSignalTitle = QtWidgets.QLabel(parent=self.chartContainerSignal)
        self.lblSignalTitle.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lblSignalTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSignalTitle.setObjectName("lblSignalTitle")
        self.layoutChartSignal.addWidget(self.lblSignalTitle)
        self.layoutObjCharts.addWidget(self.chartContainerSignal)
        self.verticalLayout_Obj1.addLayout(self.layoutObjCharts)
        self.tabWidget.addTab(self.tabObject, "")
        self.tabSituation = QtWidgets.QWidget()
        self.tabSituation.setObjectName("tabSituation")
        self.verticalLayout_Sit = QtWidgets.QVBoxLayout(self.tabSituation)
        self.verticalLayout_Sit.setObjectName("verticalLayout_Sit")
        self.layoutSitControl = QtWidgets.QHBoxLayout()
        self.layoutSitControl.setObjectName("layoutSitControl")
        self.lblSitTime = QtWidgets.QLabel(parent=self.tabSituation)
        self.lblSitTime.setObjectName("lblSitTime")
        self.layoutSitControl.addWidget(self.lblSitTime)
        self.cmbSituationTime = QtWidgets.QComboBox(parent=self.tabSituation)
        self.cmbSituationTime.setMinimumSize(QtCore.QSize(300, 0))
        self.cmbSituationTime.setObjectName("cmbSituationTime")
        self.layoutSitControl.addWidget(self.cmbSituationTime)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutSitControl.addItem(spacerItem3)
        self.verticalLayout_Sit.addLayout(self.layoutSitControl)
        self.chartContainerRadarSit = QtWidgets.QFrame(parent=self.tabSituation)
        self.chartContainerRadarSit.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.chartContainerRadarSit.setObjectName("chartContainerRadarSit")
        self.layoutChartRadarSit = QtWidgets.QVBoxLayout(self.chartContainerRadarSit)
        self.layoutChartRadarSit.setObjectName("layoutChartRadarSit")
        self.verticalLayout_Sit.addWidget(self.chartContainerRadarSit)
        self.tabWidget.addTab(self.tabSituation, "")
        self.verticalLayout_Content.addWidget(self.tabWidget)
        self.horizontalLayout_Main.addWidget(self.frameContent)

        self.retranslateUi(LogDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LogDialog)

    def retranslateUi(self, LogDialog):
        _translate = QtCore.QCoreApplication.translate
        LogDialog.setWindowTitle(_translate("LogDialog", "Аналіз історії подій"))
        self.lblSessionTitle.setStyleSheet(_translate("LogDialog", "color: #4CAF50; font-weight: bold; font-size: 18px;"))
        self.lblSessionTitle.setText(_translate("LogDialog", "Вибір сесії:"))
        self.grpFilters.setTitle(_translate("LogDialog", "Фільтри пошуку"))
        self.lblTime.setText(_translate("LogDialog", "Час:"))
        self.lblFilterName.setText(_translate("LogDialog", "Ім\'я / ID:"))
        self.inpFilterName.setPlaceholderText(_translate("LogDialog", "Введіть назву..."))
        self.lblFilterType.setText(_translate("LogDialog", "Тип події:"))
        self.lblDist.setText(_translate("LogDialog", "Дистанція (м):"))
        self.lblDash.setText(_translate("LogDialog", "-"))
        self.lblAngle.setText(_translate("LogDialog", "Кут (°):"))
        self.lblDash2.setText(_translate("LogDialog", "-"))
        self.inpTimeStart.setDisplayFormat(_translate("LogDialog", "HH:mm:ss"))
        self.inpTimeEnd.setDisplayFormat(_translate("LogDialog", "HH:mm:ss"))
        self.cmbFilterType.setItemText(0, _translate("LogDialog", "Всі"))
        self.cmbFilterType.setItemText(1, _translate("LogDialog", "Детекція (Detection)"))
        self.cmbFilterType.setItemText(2, _translate("LogDialog", "Хибна тривога (False)"))
        self.btnApplyFilters.setText(_translate("LogDialog", "Застосувати фільтри"))
        self.btnResetFilters.setText(_translate("LogDialog", "Скинути"))
        self.btnClose.setText(_translate("LogDialog", "Закрити вікно"))
        self.tableLogs.setSortingEnabled(True)
        item = self.tableLogs.horizontalHeaderItem(0)
        item.setText(_translate("LogDialog", "Час"))
        item = self.tableLogs.horizontalHeaderItem(1)
        item.setText(_translate("LogDialog", "Тип"))
        item = self.tableLogs.horizontalHeaderItem(2)
        item.setText(_translate("LogDialog", "Назва (ID)"))
        item = self.tableLogs.horizontalHeaderItem(3)
        item.setText(_translate("LogDialog", "Клас"))
        item = self.tableLogs.horizontalHeaderItem(4)
        item.setText(_translate("LogDialog", "Частота, MHz"))
        item = self.tableLogs.horizontalHeaderItem(5)
        item.setText(_translate("LogDialog", "Дист / Кут"))
        item = self.tableLogs.horizontalHeaderItem(6)
        item.setText(_translate("LogDialog", "Дійсність"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("LogDialog", "Загальний огляд"))
        self.lblChartTypeGen.setText(_translate("LogDialog", "Тип графіка:"))
        self.cmbChartTypeGeneral.setItemText(0, _translate("LogDialog", "Хронологія подій (Timeline)"))
        self.cmbChartTypeGeneral.setItemText(1, _translate("LogDialog", "Статистика класів (Bar)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneralAnalyze), _translate("LogDialog", "Загальний аналіз"))
        self.lblSelObj.setText(_translate("LogDialog", "Обрати об\'єкт:"))
        self.lblPathTitle.setText(_translate("LogDialog", "Траєкторія руху (Polar Path)"))
        self.lblSignalTitle.setText(_translate("LogDialog", "Рівень сигналу / Впевненість"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabObject), _translate("LogDialog", "Аналіз об\'єкта"))
        self.lblSitTime.setText(_translate("LogDialog", "Час відображення:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSituation), _translate("LogDialog", "Ситуація на радарі"))
