# Form implementation generated from reading ui file 'app/ui/object_manager_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ObjectManager(object):
    def setupUi(self, ObjectManager):
        ObjectManager.setObjectName("ObjectManager")
        ObjectManager.resize(1080, 700)
        ObjectManager.setStyleSheet("QDialog{\n"
"  border: 2px solid #4CAF50; \n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #002f00;\n"
"  color: #ffffff;\n"
"  font-family: \'Roboto\';\n"
"}\n"
"\n"
"/* Таблиця */\n"
"QTableWidget {\n"
"  background-color: rgba(0, 10, 0, 0.6);\n"
"  gridline-color: #328844;\n"
"  border: 1px solid #328844;\n"
"  font-size: 20px;\n"
"}\n"
"QTableWidget::item {\n"
"  padding: 5px;\n"
"}\n"
"QTableWidget::item:selected {\n"
"  background-color: #328844;\n"
"  color: #ffffff;\n"
"}\n"
"QHeaderView::section {\n"
"  background-color: #001a05;\n"
"  color: #4CAF50;\n"
"  padding: 5px;\n"
"  border: 1px solid #328844;\n"
"  font-weight: bold;\n"
"  font-size:16px;\n"
"}\n"
"\n"
"QLabel{\n"
"  font-size: 20px;\n"
"}\n"
"\n"
"/* Кнопки */\n"
"QPushButton {\n"
"  background-color: rgba(0, 20, 0, 0.8);\n"
"  border: 2px solid #328844;\n"
"  color: #ffffff;\n"
"  font-size: 20px;\n"
"  padding: 8px 15px;\n"
"  border-radius: 4px;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #328844;\n"
"  color: #000;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: #4CAF50;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgba(50, 50, 50, 0.5);\n"
"    border-color: #555;\n"
"    color: #888;\n"
"}\n"
"\n"
"QPushButton#btnDelete {\n"
"  border-color: #aa3333;\n"
"}\n"
"QPushButton#btnDelete:hover {\n"
"  background-color: #aa3333;\n"
"}\n"
"\n"
"/* Кнопка Класи - трохи інший відтінок */\n"
"QPushButton#btnManageClasses {\n"
"    background-color: rgba(0, 60, 60, 0.8);\n"
"    border-color: #328888;\n"
"}\n"
"QPushButton#btnManageClasses:hover {\n"
"    background-color: #328888;\n"
"}\n"
"\n"
"QPushButton#btnClose {\n"
"    /* Стандартний стиль */\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(ObjectManager)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_Top = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Top.setObjectName("horizontalLayout_Top")
        self.label = QtWidgets.QLabel(parent=ObjectManager)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_Top.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Top.addItem(spacerItem)
        self.btnRefresh = QtWidgets.QPushButton(parent=ObjectManager)
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout_Top.addWidget(self.btnRefresh)
        self.verticalLayout.addLayout(self.horizontalLayout_Top)
        self.tableWidget = QtWidgets.QTableWidget(parent=ObjectManager)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(190)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(190)
        self.verticalLayout.addWidget(self.tableWidget)
        self.framePagination = QtWidgets.QFrame(parent=ObjectManager)
        self.framePagination.setObjectName("framePagination")
        self.horizontalLayout_Page = QtWidgets.QHBoxLayout(self.framePagination)
        self.horizontalLayout_Page.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_Page.setObjectName("horizontalLayout_Page")
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Page.addItem(spacerItem1)
        self.btnPrevPage = QtWidgets.QPushButton(parent=self.framePagination)
        self.btnPrevPage.setObjectName("btnPrevPage")
        self.horizontalLayout_Page.addWidget(self.btnPrevPage)
        self.lblPageInfo = QtWidgets.QLabel(parent=self.framePagination)
        self.lblPageInfo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblPageInfo.setObjectName("lblPageInfo")
        self.horizontalLayout_Page.addWidget(self.lblPageInfo)
        self.btnNextPage = QtWidgets.QPushButton(parent=self.framePagination)
        self.btnNextPage.setObjectName("btnNextPage")
        self.horizontalLayout_Page.addWidget(self.btnNextPage)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Page.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.framePagination)
        self.horizontalLayout_Bottom = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Bottom.setObjectName("horizontalLayout_Bottom")
        self.btnManageClasses = QtWidgets.QPushButton(parent=ObjectManager)
        self.btnManageClasses.setObjectName("btnManageClasses")
        self.horizontalLayout_Bottom.addWidget(self.btnManageClasses)
        self.btnAdd = QtWidgets.QPushButton(parent=ObjectManager)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_Bottom.addWidget(self.btnAdd)
        self.btnEdit = QtWidgets.QPushButton(parent=ObjectManager)
        self.btnEdit.setObjectName("btnEdit")
        self.horizontalLayout_Bottom.addWidget(self.btnEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Bottom.addItem(spacerItem3)
        self.btnDelete = QtWidgets.QPushButton(parent=ObjectManager)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_Bottom.addWidget(self.btnDelete)
        self.btnClose = QtWidgets.QPushButton(parent=ObjectManager)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_Bottom.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayout_Bottom)

        self.retranslateUi(ObjectManager)
        QtCore.QMetaObject.connectSlotsByName(ObjectManager)

    def retranslateUi(self, ObjectManager):
        _translate = QtCore.QCoreApplication.translate
        ObjectManager.setWindowTitle(_translate("ObjectManager", "База об\'єктів детекції"))
        self.label.setText(_translate("ObjectManager", "Список об\'єктів"))
        self.btnRefresh.setText(_translate("ObjectManager", "Оновити"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ObjectManager", "Назва"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ObjectManager", "Клас"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ObjectManager", "Небезпека"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ObjectManager", "RF (GHz)"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ObjectManager", "Sound (Hz)"))
        self.btnPrevPage.setText(_translate("ObjectManager", "< Назад"))
        self.lblPageInfo.setStyleSheet(_translate("ObjectManager", "font-weight: bold; margin: 0 15px;"))
        self.lblPageInfo.setText(_translate("ObjectManager", "Сторінка 1 з 1"))
        self.btnNextPage.setText(_translate("ObjectManager", "Вперед >"))
        self.btnManageClasses.setText(_translate("ObjectManager", "Класи"))
        self.btnAdd.setText(_translate("ObjectManager", "Додати новий"))
        self.btnEdit.setText(_translate("ObjectManager", "Редагувати обраний"))
        self.btnDelete.setText(_translate("ObjectManager", "Видалити"))
        self.btnClose.setText(_translate("ObjectManager", "Закрити"))
