# Form implementation generated from reading ui file 'app/ui/object_editor_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ObjectEditorDialog(object):
    def setupUi(self, ObjectEditorDialog):
        ObjectEditorDialog.setObjectName("ObjectEditorDialog")
        ObjectEditorDialog.resize(550, 750)
        ObjectEditorDialog.setStyleSheet("QDialog {\n"
"    background-color: #002f00;\n"
"    color: #ffffff;\n"
"    font-family: \'Roboto\';\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox {\n"
"    background-color: rgba(0, 10, 0, 0.8);\n"
"    border: 2px solid #328844;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLineEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus, QComboBox:focus {\n"
"    border: 2px solid #4CAF50;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #ffffff;\n"
"    font-size: 16px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border: 2px solid #328844;\n"
"    background: none;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #328844;\n"
"}\n"
"\n"
"/* Секції */\n"
"QFrame#frameGeneral, QFrame#frameRF, QFrame#frameAudio {\n"
"    border: 1px solid #328844;\n"
"    background-color: rgba(0, 20, 0, 0.3);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QLabel#lblSectionTitle, QLabel#lblSectionTitle_2, QLabel#lblSectionTitle_3 {\n"
"    color: #4CAF50;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Кнопки */\n"
"QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0, 10, 0, 0.8);\n"
"    border: 2px solid #328844;\n"
"    color: #ffffff;\n"
"    font-size: 18px;\n"
"    padding: 8px;\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #328844;\n"
"    color: #002509;\n"
"}\n"
"\n"
"QPushButton#btnDelete {\n"
"    border-color: #aa3333;\n"
"    color: #ffcccc;\n"
"}\n"
"QPushButton#btnDelete:pressed {\n"
"    background-color: #aa3333;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton#btnLogout {\n"
"    border-color: #777777;\n"
"    color: #cccccc;\n"
"    font-size: 14px;\n"
"    padding: 4px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ObjectEditorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_Header = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Header.setObjectName("horizontalLayout_Header")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Header.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_Header)
        self.scrollArea = QtWidgets.QScrollArea(parent=ObjectEditorDialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 532, 652))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_Scroll = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_Scroll.setSpacing(15)
        self.verticalLayout_Scroll.setObjectName("verticalLayout_Scroll")
        self.frameGeneral = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frameGeneral.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameGeneral.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameGeneral.setObjectName("frameGeneral")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameGeneral)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblSectionTitle = QtWidgets.QLabel(parent=self.frameGeneral)
        self.lblSectionTitle.setObjectName("lblSectionTitle")
        self.verticalLayout_2.addWidget(self.lblSectionTitle)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.frameGeneral)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.inpName = QtWidgets.QLineEdit(parent=self.frameGeneral)
        self.inpName.setObjectName("inpName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inpName)
        self.label_2 = QtWidgets.QLabel(parent=self.frameGeneral)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.inpClass = QtWidgets.QComboBox(parent=self.frameGeneral)
        self.inpClass.setObjectName("inpClass")
        self.inpClass.addItem("")
        self.inpClass.addItem("")
        self.inpClass.addItem("")
        self.inpClass.addItem("")
        self.inpClass.addItem("")
        self.inpClass.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inpClass)
        self.chkDangerous = QtWidgets.QCheckBox(parent=self.frameGeneral)
        self.chkDangerous.setObjectName("chkDangerous")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chkDangerous)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_Scroll.addWidget(self.frameGeneral)
        self.frameRF = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frameRF.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameRF.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameRF.setObjectName("frameRF")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameRF)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblSectionTitle_2 = QtWidgets.QLabel(parent=self.frameRF)
        self.lblSectionTitle_2.setObjectName("lblSectionTitle_2")
        self.horizontalLayout_2.addWidget(self.lblSectionTitle_2)
        self.chkRFEnable = QtWidgets.QCheckBox(parent=self.frameRF)
        self.chkRFEnable.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.chkRFEnable.setObjectName("chkRFEnable")
        self.horizontalLayout_2.addWidget(self.chkRFEnable)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frameRF)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.inpRFFreq = QtWidgets.QDoubleSpinBox(parent=self.frameRF)
        self.inpRFFreq.setDecimals(1)
        self.inpRFFreq.setMaximum(6000.0)
        self.inpRFFreq.setProperty("value", 2400.0)
        self.inpRFFreq.setObjectName("inpRFFreq")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inpRFFreq)
        self.label_4 = QtWidgets.QLabel(parent=self.frameRF)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.inpRFBw = QtWidgets.QDoubleSpinBox(parent=self.frameRF)
        self.inpRFBw.setDecimals(1)
        self.inpRFBw.setMaximum(100.0)
        self.inpRFBw.setProperty("value", 20.0)
        self.inpRFBw.setObjectName("inpRFBw")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inpRFBw)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_Scroll.addWidget(self.frameRF)
        self.frameAudio = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frameAudio.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameAudio.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameAudio.setObjectName("frameAudio")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameAudio)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblSectionTitle_3 = QtWidgets.QLabel(parent=self.frameAudio)
        self.lblSectionTitle_3.setObjectName("lblSectionTitle_3")
        self.horizontalLayout_3.addWidget(self.lblSectionTitle_3)
        self.chkAudioEnable = QtWidgets.QCheckBox(parent=self.frameAudio)
        self.chkAudioEnable.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.chkAudioEnable.setObjectName("chkAudioEnable")
        self.horizontalLayout_3.addWidget(self.chkAudioEnable)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=self.frameAudio)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.inpAudioMin = QtWidgets.QSpinBox(parent=self.frameAudio)
        self.inpAudioMin.setMaximum(20000)
        self.inpAudioMin.setProperty("value", 100)
        self.inpAudioMin.setObjectName("inpAudioMin")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inpAudioMin)
        self.label_7 = QtWidgets.QLabel(parent=self.frameAudio)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.inpAudioMax = QtWidgets.QSpinBox(parent=self.frameAudio)
        self.inpAudioMax.setMaximum(20000)
        self.inpAudioMax.setProperty("value", 5000)
        self.inpAudioMax.setObjectName("inpAudioMax")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inpAudioMax)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.verticalLayout_Scroll.addWidget(self.frameAudio)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_Scroll.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_Footer = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Footer.setObjectName("horizontalLayout_Footer")
        self.btnDelete = QtWidgets.QPushButton(parent=ObjectEditorDialog)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_Footer.addWidget(self.btnDelete)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Footer.addItem(spacerItem2)
        self.btnCancel = QtWidgets.QPushButton(parent=ObjectEditorDialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_Footer.addWidget(self.btnCancel)
        self.btnSave = QtWidgets.QPushButton(parent=ObjectEditorDialog)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_Footer.addWidget(self.btnSave)
        self.verticalLayout.addLayout(self.horizontalLayout_Footer)

        self.retranslateUi(ObjectEditorDialog)
        QtCore.QMetaObject.connectSlotsByName(ObjectEditorDialog)

    def retranslateUi(self, ObjectEditorDialog):
        _translate = QtCore.QCoreApplication.translate
        ObjectEditorDialog.setWindowTitle(_translate("ObjectEditorDialog", "ObjectEditor"))
        self.lblSectionTitle.setText(_translate("ObjectEditorDialog", "Основна інформація"))
        self.label.setText(_translate("ObjectEditorDialog", "Назва:"))
        self.inpName.setPlaceholderText(_translate("ObjectEditorDialog", "DJI Mavic 3"))
        self.label_2.setText(_translate("ObjectEditorDialog", "Клас:"))
        self.inpClass.setItemText(0, _translate("ObjectEditorDialog", "drone"))
        self.inpClass.setItemText(1, _translate("ObjectEditorDialog", "bird"))
        self.inpClass.setItemText(2, _translate("ObjectEditorDialog", "airplane"))
        self.inpClass.setItemText(3, _translate("ObjectEditorDialog", "ufo"))
        self.inpClass.setItemText(4, _translate("ObjectEditorDialog", "interference"))
        self.inpClass.setItemText(5, _translate("ObjectEditorDialog", "other"))
        self.chkDangerous.setText(_translate("ObjectEditorDialog", "Небезпечний об\'єкт"))
        self.lblSectionTitle_2.setText(_translate("ObjectEditorDialog", "Радіо (RF)"))
        self.chkRFEnable.setText(_translate("ObjectEditorDialog", "Активувати"))
        self.label_3.setText(_translate("ObjectEditorDialog", "Частота (MHz):"))
        self.label_4.setText(_translate("ObjectEditorDialog", "Смуга (MHz):"))
        self.lblSectionTitle_3.setText(_translate("ObjectEditorDialog", "Звук (Audio)"))
        self.chkAudioEnable.setText(_translate("ObjectEditorDialog", "Активувати"))
        self.label_6.setText(_translate("ObjectEditorDialog", "Мін. частота (Hz):"))
        self.label_7.setText(_translate("ObjectEditorDialog", "Макс. частота (Hz):"))
        self.btnDelete.setText(_translate("ObjectEditorDialog", "Видалити"))
        self.btnCancel.setText(_translate("ObjectEditorDialog", "Скасувати"))
        self.btnSave.setText(_translate("ObjectEditorDialog", "Зберегти"))
