# Form implementation generated from reading ui file 'app/ui/record_status_widget.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RecordingStatusWidget(object):
    def setupUi(self, RecordingStatusWidget):
        RecordingStatusWidget.setObjectName("RecordingStatusWidget")
        RecordingStatusWidget.resize(110, 28)
        self.horizontalLayout = QtWidgets.QHBoxLayout(RecordingStatusWidget)
        self.horizontalLayout.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rec_label = QtWidgets.QLabel(parent=RecordingStatusWidget)
        self.rec_label.setStyleSheet("font-weight: bold;")
        self.rec_label.setObjectName("rec_label")
        self.horizontalLayout.addWidget(self.rec_label)
        self.duration_label = QtWidgets.QLabel(parent=RecordingStatusWidget)
        self.duration_label.setMinimumSize(QtCore.QSize(40, 0))
        self.duration_label.setStyleSheet("font-family: \'Courier New\';")
        self.duration_label.setObjectName("duration_label")
        self.horizontalLayout.addWidget(self.duration_label)
        self.pause_button = QtWidgets.QPushButton(parent=RecordingStatusWidget)
        self.pause_button.setMinimumSize(QtCore.QSize(24, 24))
        self.pause_button.setMaximumSize(QtCore.QSize(24, 24))
        self.pause_button.setText("")
        self.pause_button.setCheckable(True)
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout.addWidget(self.pause_button)

        self.retranslateUi(RecordingStatusWidget)
        QtCore.QMetaObject.connectSlotsByName(RecordingStatusWidget)

    def retranslateUi(self, RecordingStatusWidget):
        _translate = QtCore.QCoreApplication.translate
        RecordingStatusWidget.setWindowTitle(_translate("RecordingStatusWidget", "Form"))
        self.rec_label.setText(_translate("RecordingStatusWidget", "🔴"))
        self.duration_label.setText(_translate("RecordingStatusWidget", "00:00"))
