# Form implementation generated from reading ui file 'app/ui/settings_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(500, 350)
        SettingsDialog.setStyleSheet("QDialog {\n"
"  background-color: #002f00;\n"
"  color: #ffffff;\n"
"  font-family: \'Roboto\';\n"
"  border: 2px solid #4CAF50;\n"
"  border-radius: 6px;\n"
"}\n"
"\n"
"QLabel {\n"
"  color: #ffffff;\n"
"  font-size: 20px; \n"
"  font-weight: 500;\n"
"}\n"
"\n"
"QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox {\n"
"  background-color: rgba(0, 10, 0, 0.8);\n"
"  border: 1px solid #328844;\n"
"  color: #ffffff;\n"
"  padding: 3px;\n"
"  font-size: 18px;\n"
"  border-radius: 3px;\n"
"}\n"
"\n"
"/* Стрілка випадаючого списку */\n"
"QComboBox::drop-down {\n"
"   \n"
"}\n"
"QComboBox::down-arrow {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button, QSpinBox::up-button, QSpinBox::down-button {\n"
"    width: 16px;\n"
"    height: 16px;   \n"
"    padding: 2px;\n"
"}\n"
"\n"
"/* Кнопки */\n"
"QPushButton {\n"
"  border: none;\n"
"  background-color: rgba(0, 10, 0, 0.8);\n"
"  border: 1px solid #328844;\n"
"  color: #ffffff;\n"
"  font-size: 18px;\n"
"  padding: 6px;\n"
"  border-radius: 4px;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: #328844;\n"
"  color: #002509;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(parent=SettingsDialog)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.frameContent = QtWidgets.QFrame(parent=SettingsDialog)
        self.frameContent.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameContent.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameContent.setObjectName("frameContent")
        self.formLayout = QtWidgets.QFormLayout(self.frameContent)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.labelRadius = QtWidgets.QLabel(parent=self.frameContent)
        self.labelRadius.setObjectName("labelRadius")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelRadius)
        self.inpMaxRadius = QtWidgets.QDoubleSpinBox(parent=self.frameContent)
        self.inpMaxRadius.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.inpMaxRadius.setMaximum(1000.0)
        self.inpMaxRadius.setProperty("value", 50.0)
        self.inpMaxRadius.setObjectName("inpMaxRadius")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inpMaxRadius)
        self.labelGps = QtWidgets.QLabel(parent=self.frameContent)
        self.labelGps.setObjectName("labelGps")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelGps)
        self.labelRelay = QtWidgets.QLabel(parent=self.frameContent)
        self.labelRelay.setObjectName("labelRelay")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelRelay)
        self.cmbRelay = QtWidgets.QComboBox(parent=self.frameContent)
        self.cmbRelay.setObjectName("cmbRelay")
        self.cmbRelay.addItem("")
        self.cmbRelay.addItem("")
        self.cmbRelay.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cmbRelay)
        self.inpGpsInterval = QtWidgets.QDoubleSpinBox(parent=self.frameContent)
        self.inpGpsInterval.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.inpGpsInterval.setMinimum(0.5)
        self.inpGpsInterval.setProperty("value", 5.0)
        self.inpGpsInterval.setObjectName("inpGpsInterval")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inpGpsInterval)
        self.verticalLayout.addWidget(self.frameContent)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_Footer = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Footer.setObjectName("horizontalLayout_Footer")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Footer.addItem(spacerItem1)
        self.btnCancel = QtWidgets.QPushButton(parent=SettingsDialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_Footer.addWidget(self.btnCancel)
        self.btnSave = QtWidgets.QPushButton(parent=SettingsDialog)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_Footer.addWidget(self.btnSave)
        self.verticalLayout.addLayout(self.horizontalLayout_Footer)

        self.retranslateUi(SettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Налаштування"))
        self.lblTitle.setStyleSheet(_translate("SettingsDialog", "font-size: 24px; font-weight: bold; margin-bottom: 10px;"))
        self.lblTitle.setText(_translate("SettingsDialog", "Налаштування"))
        self.labelRadius.setText(_translate("SettingsDialog", "Макс. радіус радару (км):"))
        self.labelGps.setText(_translate("SettingsDialog", "Інтервал GPS (хв):"))
        self.labelRelay.setText(_translate("SettingsDialog", "Основне реле:"))
        self.cmbRelay.setItemText(0, _translate("SettingsDialog", "K1"))
        self.cmbRelay.setItemText(1, _translate("SettingsDialog", "K2"))
        self.cmbRelay.setItemText(2, _translate("SettingsDialog", "K3"))
        self.btnCancel.setText(_translate("SettingsDialog", "Скасувати"))
        self.btnSave.setText(_translate("SettingsDialog", "Зберегти"))
