from typing import Any, Tuple

from PyQt6.QtWidgets import QGraphicsScene, QWidget

class PlotItem:
    vb: Any
    def showGrid(self, x: bool = ..., y: bool = ..., alpha: float = ...) -> None: ...
    def setLabel(self, axis: str, text: str, units: str = ...) -> None: ...
    def setYRange(self, min: float, max: float) -> None: ...
    def setXRange(self, min: float, max: float) -> None: ...
    def enableAutoRange(self) -> None: ...
    def setVisible(self, visible: bool) -> None: ...
    def plot(self, pen: Any = ...) -> Any: ...
    def sceneBoundingRect(self) -> Any: ...
    # Додано **kwargs, щоб працював параметр ignoreBounds
    def addItem(self, item: Any, **kwargs: Any) -> None: ...

class GraphicsScene(QGraphicsScene):
    class Signal:
        def connect(self, slot: Any) -> None: ...

    # Явно вказуємо, що у сцени pyqtgraph є цей сигнал
    sigMouseMoved: Signal

class GraphicsLayoutWidget(QWidget):
    def addPlot(self, title: str = ...) -> PlotItem: ...
    def nextRow(self) -> None: ...
    # Перевизначаємо метод scene, щоб він повертав сцену pyqtgraph
    def scene(self) -> GraphicsScene: ...

class ImageItem:
    def setLookupTable(self, lut: Any) -> None: ...
    def setImage(
        self, image: Any, autoLevels: bool = ..., levels: Tuple[int, int] = ...
    ) -> None: ...
    def setRect(self, rect: Any) -> None: ...
    def resetTransform(self) -> None: ...

class ColorMap:
    def __init__(self, pos: Any, color: Any) -> None: ...
    def getLookupTable(self, start: float, stop: float, pts: int) -> Any: ...

class InfiniteLine:
    def __init__(
        self,
        pos: Any = ...,
        angle: float = ...,
        pen: Any = ...,
        movable: bool = ...,
        bounds: Any = ...,
        hoverPen: Any = ...,
        label: Any = ...,
        labelOpts: Any = ...,
        name: Any = ...,
    ) -> None: ...
    def setPos(self, pos: Any) -> None: ...
    def isVisible(self) -> bool: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...

class TextItem:
    def __init__(
        self,
        text: str = ...,
        color: Any = ...,
        html: str = ...,
        anchor: Tuple[float, float] = ...,
        border: Any = ...,
        fill: Any = ...,
        angle: float = ...,
        rotateAxis: Any = ...,
    ) -> None: ...
    def setText(self, text: str) -> None: ...
    def setPos(self, x: float, y: float) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...

# Глобальні функції конфігурації та стилізації
def setConfigOption(opt: str, value: Any) -> None: ...
def setConfigOptions(**kwargs: Any) -> None: ...

# Додано **kwargs для параметра style
def mkPen(color: Any, width: int = ..., **kwargs: Any) -> Any: ...

# Додано mkBrush
def mkBrush(*args: Any, **kwargs: Any) -> Any: ...
