# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sdr_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1920, 1080))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setStyleSheet("background-image: url(:/Images/images/bg.png)")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Header = QtWidgets.QFrame(self.centralwidget)
        self.Header.setEnabled(True)
        self.Header.setGeometry(QtCore.QRect(0, 0, 1920, 94))
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.HeaderBack = QtWidgets.QLabel(self.Header)
        self.HeaderBack.setGeometry(QtCore.QRect(0, 0, 1920, 94))
        self.HeaderBack.setStyleSheet("background: rgba(0, 10, 0, 0.8);\n"
"border: 3px solid #328844;")
        self.HeaderBack.setText("")
        self.HeaderBack.setObjectName("HeaderBack")
        self.DateLabel = QtWidgets.QLabel(self.Header)
        self.DateLabel.setGeometry(QtCore.QRect(30, 14, 141, 29))
        self.DateLabel.setStyleSheet("position: absolute;\n"
"left: 1.56%;\n"
"right: 91.09%;\n"
"top: 14.89%;\n"
"bottom: 14.89%;\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 24px;\n"
"line-height: 33px;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;\n"
"background: rgba(0, 10, 0, 0.1);")
        self.DateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DateLabel.setWordWrap(False)
        self.DateLabel.setObjectName("DateLabel")
        self.BandsAvailable = QtWidgets.QFrame(self.Header)
        self.BandsAvailable.setGeometry(QtCore.QRect(773, 9, 468, 78))
        self.BandsAvailable.setStyleSheet("border: 2px solid #328843;\n"
"background: rgba(0, 10, 0, 0.1);")
        self.BandsAvailable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BandsAvailable.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BandsAvailable.setObjectName("BandsAvailable")
        self.ghz58_1 = QtWidgets.QLabel(self.BandsAvailable)
        self.ghz58_1.setGeometry(QtCore.QRect(0, 0, 117, 39))
        self.ghz58_1.setStyleSheet("*[band_active=\"true\"] { \n"
"border: 2px solid #328843;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #50E37F;\n"
"}\n"
"\n"
"*[band_active=\"false\"] { \n"
"border: 2px solid #328843;\n"
"background-image: url(:/Images/images/band_inactive.png);\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #FF2828;\n"
"}")
        self.ghz58_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ghz58_1.setProperty("band_active", True)
        self.ghz58_1.setObjectName("ghz58_1")
        self.ghz58_2 = QtWidgets.QLabel(self.BandsAvailable)
        self.ghz58_2.setGeometry(QtCore.QRect(117, 0, 117, 39))
        self.ghz58_2.setStyleSheet("*[band_active=\"true\"] { \n"
"border: 2px solid #328843;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #50E37F;\n"
"}\n"
"\n"
"*[band_active=\"false\"] { \n"
"border: 2px solid #328843;\n"
"background-image: url(:/Images/images/band_inactive.png);\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #FF2828;\n"
"}")
        self.ghz58_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ghz58_2.setProperty("band_active", True)
        self.ghz58_2.setObjectName("ghz58_2")
        self.ghz58_3 = QtWidgets.QLabel(self.BandsAvailable)
        self.ghz58_3.setGeometry(QtCore.QRect(234, 0, 117, 39))
        self.ghz58_3.setStyleSheet("*[band_active=\"true\"] { \n"
"border: 2px solid #328843;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #50E37F;\n"
"}\n"
"\n"
"*[band_active=\"false\"] { \n"
"border: 2px solid #328843;\n"
"background-image: url(:/Images/images/band_inactive.png);\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #FF2828;\n"
"}")
        self.ghz58_3.setAlignment(QtCore.Qt.AlignCenter)
        self.ghz58_3.setProperty("band_active", False)
        self.ghz58_3.setObjectName("ghz58_3")
        self.ghz58_4 = QtWidgets.QLabel(self.BandsAvailable)
        self.ghz58_4.setGeometry(QtCore.QRect(351, 0, 117, 39))
        self.ghz58_4.setStyleSheet("*[band_active=\"true\"] { \n"
"border: 2px solid #328843;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #50E37F;\n"
"}\n"
"\n"
"*[band_active=\"false\"] { \n"
"border: 2px solid #328843;\n"
"background-image: url(:/Images/images/band_inactive.png);\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #FF2828;\n"
"}")
        self.ghz58_4.setAlignment(QtCore.Qt.AlignCenter)
        self.ghz58_4.setProperty("band_active", True)
        self.ghz58_4.setObjectName("ghz58_4")
        self.ghz24_1 = QtWidgets.QLabel(self.BandsAvailable)
        self.ghz24_1.setGeometry(QtCore.QRect(0, 39, 117, 39))
        self.ghz24_1.setStyleSheet("*[band_active=\"true\"] { \n"
"border: 2px solid #328843;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #50E37F;\n"
"}\n"
"\n"
"*[band_active=\"false\"] { \n"
"border: 2px solid #328843;\n"
"background-image: url(:/Images/images/band_inactive.png);\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #FF2828;\n"
"}")
        self.ghz24_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ghz24_1.setProperty("band_active", True)
        self.ghz24_1.setObjectName("ghz24_1")
        self.ghz24_2 = QtWidgets.QLabel(self.BandsAvailable)
        self.ghz24_2.setGeometry(QtCore.QRect(117, 39, 117, 39))
        self.ghz24_2.setStyleSheet("*[band_active=\"true\"] { \n"
"border: 2px solid #328843;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #50E37F;\n"
"}\n"
"\n"
"*[band_active=\"false\"] { \n"
"border: 2px solid #328843;\n"
"background-image: url(:/Images/images/band_inactive.png);\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #FF2828;\n"
"}")
        self.ghz24_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ghz24_2.setProperty("band_active", False)
        self.ghz24_2.setObjectName("ghz24_2")
        self.ghz24_3 = QtWidgets.QLabel(self.BandsAvailable)
        self.ghz24_3.setGeometry(QtCore.QRect(234, 39, 117, 39))
        self.ghz24_3.setStyleSheet("*[band_active=\"true\"] { \n"
"border: 2px solid #328843;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #50E37F;\n"
"}\n"
"\n"
"*[band_active=\"false\"] { \n"
"border: 2px solid #328843;\n"
"background-image: url(:/Images/images/band_inactive.png);\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #FF2828;\n"
"}")
        self.ghz24_3.setAlignment(QtCore.Qt.AlignCenter)
        self.ghz24_3.setProperty("band_active", False)
        self.ghz24_3.setObjectName("ghz24_3")
        self.ghz24_4 = QtWidgets.QLabel(self.BandsAvailable)
        self.ghz24_4.setGeometry(QtCore.QRect(351, 39, 117, 39))
        self.ghz24_4.setStyleSheet("*[band_active=\"true\"] { \n"
"border: 2px solid #328843;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #50E37F;\n"
"}\n"
"\n"
"*[band_active=\"false\"] { \n"
"border: 2px solid #328843;\n"
"background-image: url(:/Images/images/band_inactive.png);\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 26px;\n"
"line-height: 95%;\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"color: #FF2828;\n"
"}")
        self.ghz24_4.setAlignment(QtCore.Qt.AlignCenter)
        self.ghz24_4.setProperty("band_active", False)
        self.ghz24_4.setObjectName("ghz24_4")
        self.RF_alert = QtWidgets.QLabel(self.Header)
        self.RF_alert.setGeometry(QtCore.QRect(1269, 9, 267, 76))
        self.RF_alert.setStyleSheet("*{font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 30px;\n"
"line-height: 100%;\n"
"/* identical to box height, or 34px */\n"
"\n"
"display: flex;\n"
"align-items: center;\n"
"letter-spacing: -0.01em;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"text-shadow: 0px 3px 4px rgba(63, 0, 0, 0.5);\n"
"}\n"
"\n"
"*[alert=\"true\"]{\n"
"background-image: url(:/Images/images/rf_alert_on.png);\n"
"}\n"
"\n"
"*[alert=\"false\"]{\n"
"background-image: url(:/Images/images/rf_alert_off.png);\n"
"}")
        self.RF_alert.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RF_alert.setProperty("alert", False)
        self.RF_alert.setObjectName("RF_alert")
        self.Sound_alert = QtWidgets.QLabel(self.Header)
        self.Sound_alert.setGeometry(QtCore.QRect(1568, 9, 322, 76))
        self.Sound_alert.setStyleSheet("*{font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 30px;\n"
"line-height: 100%;\n"
"/* identical to box height, or 34px */\n"
"\n"
"display: flex;\n"
"align-items: center;\n"
"letter-spacing: -0.01em;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"text-shadow: 0px 3px 4px rgba(63, 0, 0, 0.5);\n"
"}\n"
"\n"
"*[alert=\"true\"]{\n"
"background-image: url(:/Images/images/sound_alert_on.png);\n"
"}\n"
"\n"
"*[alert=\"false\"]{\n"
"background-image: url(:/Images/images/sound_alert_off.png);\n"
"}")
        self.Sound_alert.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Sound_alert.setProperty("alert", True)
        self.Sound_alert.setObjectName("Sound_alert")
        self.GPS = QtWidgets.QFrame(self.Header)
        self.GPS.setGeometry(QtCore.QRect(251, 17, 198, 60))
        self.GPS.setStyleSheet("border: none;\n"
"background: rgba(0, 10, 0, 0.1);")
        self.GPS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GPS.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GPS.setLineWidth(1)
        self.GPS.setObjectName("GPS")
        self.label = QtWidgets.QLabel(self.GPS)
        self.label.setGeometry(QtCore.QRect(0, 0, 99, 60))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("/* GPS */\n"
"width: 99px;\n"
"height: 60px;\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 48px;\n"
"line-height: 60px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"\n"
"/* Inside auto layout */\n"
"\n"
"flex: none;\n"
"order: 0;\n"
"flex-grow: 0;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.GPS_level = QtWidgets.QLabel(self.GPS)
        self.GPS_level.setGeometry(QtCore.QRect(122, 10, 76, 39))
        self.GPS_level.setStyleSheet("*[level=\"0\"] { background-image: url(:/Images/images/level_0.png) }\n"
"*[level=\"1\"] { background-image: url(:/Images/images/level_1.png) }\n"
"*[level=\"2\"] { background-image: url(:/Images/images/level_2.png) }\n"
"*[level=\"3\"] { background-image: url(:/Images/images/level_3.png) }\n"
"*[level=\"4\"] { background-image: url(:/Images/images/level_4.png) }")
        self.GPS_level.setText("")
        self.GPS_level.setProperty("level", 4)
        self.GPS_level.setObjectName("GPS_level")
        self.WiFi = QtWidgets.QFrame(self.Header)
        self.WiFi.setGeometry(QtCore.QRect(481, 17, 198, 60))
        self.WiFi.setStyleSheet("border: none;\n"
"background: rgba(0, 10, 0, 0.1);")
        self.WiFi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WiFi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WiFi.setLineWidth(1)
        self.WiFi.setObjectName("WiFi")
        self.label_2 = QtWidgets.QLabel(self.WiFi)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 111, 60))
        self.label_2.setStyleSheet("/* GPS */\n"
"width: 99px;\n"
"height: 60px;\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 48px;\n"
"line-height: 60px;\n"
"/* identical to box height */\n"
"\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"\n"
"/* Inside auto layout */\n"
"\n"
"flex: none;\n"
"order: 0;\n"
"flex-grow: 0;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.WiFi_level = QtWidgets.QLabel(self.WiFi)
        self.WiFi_level.setGeometry(QtCore.QRect(122, 10, 76, 39))
        self.WiFi_level.setStyleSheet("*[level=\"0\"] { background-image: url(:/Images/images/level_0.png) }*[level=\"1\"] { background-image: url(:/Images/images/level_1.png) }*[level=\"2\"] { background-image: url(:/Images/images/level_2.png) }*[level=\"3\"] { background-image: url(:/Images/images/level_3.png) }*[level=\"4\"] { background-image: url(:/Images/images/level_4.png) }")
        self.WiFi_level.setText("")
        self.WiFi_level.setProperty("level", 2)
        self.WiFi_level.setObjectName("WiFi_level")
        self.TimeLabel = QtWidgets.QLabel(self.Header)
        self.TimeLabel.setGeometry(QtCore.QRect(30, 50, 141, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TimeLabel.setFont(font)
        self.TimeLabel.setStyleSheet("position: absolute;\n"
"left: 1.56%;\n"
"right: 91.09%;\n"
"top: 14.89%;\n"
"bottom: 14.89%;\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 24px;\n"
"line-height: 33px;\n"
"text-align: center;\n"
"\n"
"color: #FFFFFF;\n"
"background: rgba(0, 10, 0, 0.1);")
        self.TimeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.TimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeLabel.setWordWrap(False)
        self.TimeLabel.setObjectName("TimeLabel")
        self.Body = QtWidgets.QFrame(self.centralwidget)
        self.Body.setEnabled(True)
        self.Body.setGeometry(QtCore.QRect(0, 95, 1920, 985))
        self.Body.setStyleSheet("border: none;\n"
"background: none;")
        self.Body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Body.setObjectName("Body")
        self.homeButton = QtWidgets.QPushButton(self.Body)
        self.homeButton.setEnabled(True)
        self.homeButton.setGeometry(QtCore.QRect(30, 573, 110, 110))
        self.homeButton.setStyleSheet("QPushButton#homeButton{\n"
"    background-image: url(:/Images/images/homeBtn_off.png);\n"
"}\n"
"\n"
"QPushButton#homeButton:pressed{\n"
"    background-image: url(:/Images/images/homeBtn_on.png);\n"
"}\n"
"\n"
"QPushButton#homeButton[enabled=\"false\"]{\n"
"    background-image: url(:/Images/images/homeBtn_disabled.png);\n"
"}")
        self.homeButton.setText("")
        self.homeButton.setAutoDefault(False)
        self.homeButton.setFlat(False)
        self.homeButton.setObjectName("homeButton")
        self.mapLayoutButton = QtWidgets.QPushButton(self.Body)
        self.mapLayoutButton.setEnabled(True)
        self.mapLayoutButton.setGeometry(QtCore.QRect(30, 709, 110, 110))
        self.mapLayoutButton.setStyleSheet("QPushButton#mapLayoutButton{\n"
"    background-image: url(:/Images/images/map_layout_off.png);\n"
"}\n"
"\n"
"QPushButton#mapLayoutButton:pressed{\n"
"    background-image: url(:/Images/images/map_layout_on.png);\n"
"}\n"
"\n"
"QPushButton#mapLayoutButton[enabled=\"false\"]{\n"
"    background-image: url(:/Images/images/map_layout_disabled.png);\n"
"}")
        self.mapLayoutButton.setText("")
        self.mapLayoutButton.setAutoDefault(False)
        self.mapLayoutButton.setFlat(False)
        self.mapLayoutButton.setObjectName("mapLayoutButton")
        self.screenSaveButton = QtWidgets.QPushButton(self.Body)
        self.screenSaveButton.setEnabled(True)
        self.screenSaveButton.setGeometry(QtCore.QRect(30, 845, 110, 110))
        self.screenSaveButton.setStyleSheet("QPushButton#screenSaveButton{\n"
"    background-image: url(:/Images/images/screen_save_off.png);\n"
"}\n"
"\n"
"QPushButton#screenSaveButton:pressed{\n"
"    background-image: url(:/Images/images/screen_save_on.png);\n"
"}\n"
"\n"
"QPushButton#screenSaveButton[enabled=\"false\"]{\n"
"    background-image: url(:/Images/images/screen_save_disabled.png);\n"
"}")
        self.screenSaveButton.setText("")
        self.screenSaveButton.setAutoDefault(False)
        self.screenSaveButton.setFlat(False)
        self.screenSaveButton.setObjectName("screenSaveButton")
        self.MainButtons = QtWidgets.QFrame(self.Body)
        self.MainButtons.setGeometry(QtCore.QRect(1538, 0, 382, 393))
        self.MainButtons.setStyleSheet("background: rgba(0, 10, 0, 0.8);\n"
"border: 2px solid #328844;")
        self.MainButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainButtons.setObjectName("MainButtons")
        self.radarButton = QtWidgets.QPushButton(self.MainButtons)
        self.radarButton.setEnabled(True)
        self.radarButton.setGeometry(QtCore.QRect(30, 25, 322, 103))
        self.radarButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-image: url(:/Images/images/Btn_MainMenu_off.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 36px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked{\n"
"    border: none;\n"
"    background-image: url(:/Images/images/Btn_MainMenu_on.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 36px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #002509;\n"
"}\n"
"\n"
"QPushButton[enabled=\"false\"]{\n"
"    border: none;\n"
"    background-image: url(:/Images/images/Btn_MainMenu_disabled.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 36px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #FFFFFF;\n"
"}")
        self.radarButton.setCheckable(True)
        self.radarButton.setChecked(False)
        self.radarButton.setAutoExclusive(True)
        self.radarButton.setObjectName("radarButton")
        self.mapButton = QtWidgets.QPushButton(self.MainButtons)
        self.mapButton.setEnabled(True)
        self.mapButton.setGeometry(QtCore.QRect(30, 145, 322, 103))
        self.mapButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-image: url(:/Images/images/Btn_MainMenu_off.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 36px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked{\n"
"    border: none;\n"
"    background-image: url(:/Images/images/Btn_MainMenu_on.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 36px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #002509;\n"
"}\n"
"\n"
"QPushButton[enabled=\"false\"]{\n"
"    border: none;\n"
"    background-image: url(:/Images/images/Btn_MainMenu_disabled.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 36px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #FFFFFF;\n"
"}")
        self.mapButton.setCheckable(True)
        self.mapButton.setChecked(True)
        self.mapButton.setAutoExclusive(True)
        self.mapButton.setObjectName("mapButton")
        self.menuButton = QtWidgets.QPushButton(self.MainButtons)
        self.menuButton.setEnabled(True)
        self.menuButton.setGeometry(QtCore.QRect(30, 265, 322, 103))
        self.menuButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menuButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-image: url(:/Images/images/Btn_MainMenu_off.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 36px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: none;\n"
"    background-image: url(:/Images/images/Btn_MainMenu_on.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 36px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #002509;\n"
"}\n"
"\n"
"QPushButton[enabled=\"false\"]{\n"
"    border: none;\n"
"    background-image: url(:/Images/images/Btn_MainMenu_disabled.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 36px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #FFFFFF;\n"
"}")
        self.menuButton.setCheckable(False)
        self.menuButton.setChecked(False)
        self.menuButton.setAutoExclusive(False)
        self.menuButton.setObjectName("menuButton")
        self.TimerFrame = QtWidgets.QFrame(self.Body)
        self.TimerFrame.setGeometry(QtCore.QRect(1538, 553, 382, 432))
        self.TimerFrame.setStyleSheet("background: rgba(0, 10, 0, 0.8);\n"
"border: 2px solid #328844;")
        self.TimerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TimerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TimerFrame.setObjectName("TimerFrame")
        self.label_3 = QtWidgets.QLabel(self.TimerFrame)
        self.label_3.setGeometry(QtCore.QRect(127, 8, 127, 40))
        self.label_3.setStyleSheet("background: none;\n"
"border: none;\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 34px;\n"
"line-height: 40px;\n"
"text-align: center;\n"
"\n"
"color: #FFF500;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.TimerTime = QtWidgets.QLabel(self.TimerFrame)
        self.TimerTime.setGeometry(QtCore.QRect(76, 52, 229, 68))
        self.TimerTime.setStyleSheet("background: none;\n"
"border: none;\n"
"\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 52px;\n"
"line-height: 68px;\n"
"\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"\n"
"color: #E4E7E4;\n"
"")
        self.TimerTime.setAlignment(QtCore.Qt.AlignCenter)
        self.TimerTime.setObjectName("TimerTime")
        self.onTimerButton = QtWidgets.QPushButton(self.TimerFrame)
        self.onTimerButton.setGeometry(QtCore.QRect(30, 312, 322, 90))
        self.onTimerButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-image: url(:/Images/images/Btn_MainMenu_off.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 36px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: none;\n"
"    border-image: url(:/Images/images/Btn_MainMenu_on.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 36px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #002509;\n"
"}\n"
"\n"
"QPushButton[enabled=\"false\"]{\n"
"    border: none;\n"
"    border-image: url(:/Images/images/Btn_MainMenu_disabled.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 36px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #FFFFFF;\n"
"}")
        self.onTimerButton.setObjectName("onTimerButton")
        self.offTimerButton = QtWidgets.QPushButton(self.TimerFrame)
        self.offTimerButton.setGeometry(QtCore.QRect(30, 132, 322, 166))
        self.offTimerButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-image: url(:/Images/images/Btn_MainMenu_red.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 52px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: none;\n"
"    border-image: url(:/Images/images/Btn_MainMenu_on.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 52px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #002509;\n"
"}\n"
"\n"
"QPushButton[enabled=\"false\"]{\n"
"    border: none;\n"
"    border-image: url(:/Images/images/Btn_MainMenu_disabled.png);\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 52px;\n"
"    line-height: 100%;\n"
"    display: flex;\n"
"    align-items: center;\n"
"    text-align: center;\n"
"    letter-spacing: -0.01em;\n"
"    color: #FFFFFF;\n"
"}")
        self.offTimerButton.setObjectName("offTimerButton")
        self.k_label_1 = QtWidgets.QLabel(self.Body)
        self.k_label_1.setEnabled(False)
        self.k_label_1.setGeometry(QtCore.QRect(1550, 453, 102, 101))
        self.k_label_1.setStyleSheet("*{\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 38px;\n"
"    line-height: 45px;\n"
"    text-align: center;\n"
"\n"
"    color: #FFFFFF;\n"
"\n"
"    text-border: 1px solid #0B5A1A;\n"
"    text-shadow: 0px 1px 0px #025613;\n"
"}\n"
"\n"
"*[enabled=\"true\"]\n"
"{\n"
"    background-image: url(:/Images/images/k_relay_on.png);\n"
"}\n"
"\n"
"*[enabled=\"false\"]\n"
"{\n"
"    background-image: url(:/Images/images/k_relay_off.png);\n"
"}")
        self.k_label_1.setScaledContents(False)
        self.k_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.k_label_1.setObjectName("k_label_1")
        self.k_label_2 = QtWidgets.QLabel(self.Body)
        self.k_label_2.setEnabled(False)
        self.k_label_2.setGeometry(QtCore.QRect(1678, 453, 102, 101))
        self.k_label_2.setStyleSheet("*{\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 38px;\n"
"    line-height: 45px;\n"
"    text-align: center;\n"
"\n"
"    color: #FFFFFF;\n"
"\n"
"    text-border: 1px solid #0B5A1A;\n"
"    text-shadow: 0px 1px 0px #025613;\n"
"}\n"
"\n"
"*[enabled=\"true\"]\n"
"{\n"
"    background-image: url(:/Images/images/k_relay_on.png);\n"
"}\n"
"\n"
"*[enabled=\"false\"]\n"
"{\n"
"    background-image: url(:/Images/images/k_relay_off.png);\n"
"}")
        self.k_label_2.setScaledContents(False)
        self.k_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.k_label_2.setObjectName("k_label_2")
        self.k_label_3 = QtWidgets.QLabel(self.Body)
        self.k_label_3.setEnabled(False)
        self.k_label_3.setGeometry(QtCore.QRect(1806, 453, 102, 101))
        self.k_label_3.setStyleSheet("*{\n"
"    font-family: \'Roboto\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 38px;\n"
"    line-height: 45px;\n"
"    text-align: center;\n"
"\n"
"    color: #FFFFFF;\n"
"\n"
"    text-border: 1px solid #0B5A1A;\n"
"    text-shadow: 0px 1px 0px #025613;\n"
"}\n"
"\n"
"*[enabled=\"true\"]\n"
"{\n"
"    background-image: url(:/Images/images/k_relay_on.png);\n"
"}\n"
"\n"
"*[enabled=\"false\"]\n"
"{\n"
"    background-image: url(:/Images/images/k_relay_off.png);\n"
"}")
        self.k_label_3.setScaledContents(False)
        self.k_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.k_label_3.setObjectName("k_label_3")
        self.RadarFrame = QtWidgets.QFrame(self.Body)
        self.RadarFrame.setGeometry(QtCore.QRect(509, 25, 901, 901))
        self.RadarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RadarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RadarFrame.setObjectName("RadarFrame")
        self.Radar = QtWidgets.QLabel(self.RadarFrame)
        self.Radar.setGeometry(QtCore.QRect(0, 0, 901, 901))
        self.Radar.setText("")
        self.Radar.setPixmap(QtGui.QPixmap(":/Images/images/radar.png"))
        self.Radar.setObjectName("Radar")
        self.Radar_Green = QtWidgets.QLabel(self.RadarFrame)
        self.Radar_Green.setGeometry(QtCore.QRect(0, 0, 901, 901))
        self.Radar_Green.setText("")
        self.Radar_Green.setPixmap(QtGui.QPixmap(":/Images/images/radar_green.png"))
        self.Radar_Green.setAlignment(QtCore.Qt.AlignCenter)
        self.Radar_Green.setObjectName("Radar_Green")
        self.Radar_Red = QtWidgets.QLabel(self.RadarFrame)
        self.Radar_Red.setGeometry(QtCore.QRect(0, 0, 901, 901))
        self.Radar_Red.setText("")
        self.Radar_Red.setPixmap(QtGui.QPixmap(":/Images/images/radar_red.png"))
        self.Radar_Red.setAlignment(QtCore.Qt.AlignCenter)
        self.Radar_Red.setObjectName("Radar_Red")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DateLabel.setText(_translate("MainWindow", "05.01.2022"))
        self.ghz58_1.setText(_translate("MainWindow", "5.8GHz"))
        self.ghz58_2.setText(_translate("MainWindow", "5.8GHz"))
        self.ghz58_3.setText(_translate("MainWindow", "5.8GHz"))
        self.ghz58_4.setText(_translate("MainWindow", "5.8GHz"))
        self.ghz24_1.setText(_translate("MainWindow", "2.4GHz"))
        self.ghz24_2.setText(_translate("MainWindow", "2.4GHz"))
        self.ghz24_3.setText(_translate("MainWindow", "2.4GHz"))
        self.ghz24_4.setText(_translate("MainWindow", "2.4GHz"))
        self.RF_alert.setText(_translate("MainWindow", "Тривога RF"))
        self.Sound_alert.setText(_translate("MainWindow", "Тривога Sound"))
        self.label.setText(_translate("MainWindow", "GPS"))
        self.label_2.setText(_translate("MainWindow", "Wi Fi"))
        self.TimeLabel.setText(_translate("MainWindow", "17:54"))
        self.radarButton.setText(_translate("MainWindow", "Режим радару"))
        self.mapButton.setText(_translate("MainWindow", "Режим карти"))
        self.menuButton.setText(_translate("MainWindow", "Меню"))
        self.label_3.setText(_translate("MainWindow", "Jammer"))
        self.TimerTime.setText(_translate("MainWindow", "00:00:00"))
        self.onTimerButton.setText(_translate("MainWindow", "ON"))
        self.offTimerButton.setText(_translate("MainWindow", "OFF"))
        self.k_label_1.setText(_translate("MainWindow", "K1"))
        self.k_label_2.setText(_translate("MainWindow", "K2"))
        self.k_label_3.setText(_translate("MainWindow", "K3"))
import UI.source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
